// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type Platforms struct {
	Signature string `json:"signature"`
	URL       string `json:"url"`
}

func (o *Platforms) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *Platforms) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

// CheckDesktopUpdateResponseBody - Update manifest in Tauri updater format
type CheckDesktopUpdateResponseBody struct {
	Version   string               `json:"version"`
	Notes     *string              `json:"notes,omitempty"`
	PubDate   *string              `json:"pub_date,omitempty"`
	Platforms map[string]Platforms `json:"platforms"`
}

func (o *CheckDesktopUpdateResponseBody) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

func (o *CheckDesktopUpdateResponseBody) GetNotes() *string {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *CheckDesktopUpdateResponseBody) GetPubDate() *string {
	if o == nil {
		return nil
	}
	return o.PubDate
}

func (o *CheckDesktopUpdateResponseBody) GetPlatforms() map[string]Platforms {
	if o == nil {
		return map[string]Platforms{}
	}
	return o.Platforms
}

type CheckDesktopUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update manifest in Tauri updater format
	Object *CheckDesktopUpdateResponseBody
}

func (o *CheckDesktopUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CheckDesktopUpdateResponse) GetObject() *CheckDesktopUpdateResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
