// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// CreateBankAccountRequest - Schema for creating a new bank account.
type CreateBankAccountRequest struct {
	// The name of the bank account.
	Name string `json:"name"`
	// The currency code for the bank account (ISO 4217).
	Currency *string `json:"currency,omitempty"`
	// Whether the bank account is a manual account.
	Manual *bool `json:"manual,omitempty"`
}

func (o *CreateBankAccountRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateBankAccountRequest) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateBankAccountRequest) GetManual() *bool {
	if o == nil {
		return nil
	}
	return o.Manual
}

// CreateBankAccountResponseBody - A single bank account object response.
type CreateBankAccountResponseBody struct {
	// Unique identifier for the bank account.
	ID string `json:"id"`
	// Name of the bank account.
	Name *string `json:"name"`
	// Currency code of the bank account (e.g., USD, EUR).
	Currency *string `json:"currency"`
	// Type of the bank account (e.g., depository, credit).
	Type *string `json:"type"`
	// Whether the bank account is enabled.
	Enabled bool `json:"enabled"`
	// Current balance of the bank account.
	Balance *float64 `json:"balance"`
	// Whether the bank account is a manual account.
	Manual *bool `json:"manual"`
}

func (o *CreateBankAccountResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateBankAccountResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateBankAccountResponseBody) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateBankAccountResponseBody) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *CreateBankAccountResponseBody) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *CreateBankAccountResponseBody) GetBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *CreateBankAccountResponseBody) GetManual() *bool {
	if o == nil {
		return nil
	}
	return o.Manual
}

type CreateBankAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bank account created
	Object *CreateBankAccountResponseBody
}

func (o *CreateBankAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateBankAccountResponse) GetObject() *CreateBankAccountResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
