// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

type CreateTrackerEntryRequest struct {
	// Start time of the tracker entry in ISO 8601 format
	Start time.Time `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop time.Time `json:"stop"`
	// Array of dates for which to create tracker entries
	Dates []string `json:"dates"`
	// Unique identifier of the user assigned to this tracker entry
	AssignedID *string `json:"assignedId"`
	// Unique identifier of the project associated with this tracker entry
	ProjectID string `json:"projectId"`
	// Optional description or notes for the tracker entry
	Description *string `json:"description,omitempty"`
	// Duration of the tracker entry in seconds
	Duration float64 `json:"duration"`
}

func (c CreateTrackerEntryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTrackerEntryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateTrackerEntryRequest) GetStart() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Start
}

func (o *CreateTrackerEntryRequest) GetStop() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Stop
}

func (o *CreateTrackerEntryRequest) GetDates() []string {
	if o == nil {
		return []string{}
	}
	return o.Dates
}

func (o *CreateTrackerEntryRequest) GetAssignedID() *string {
	if o == nil {
		return nil
	}
	return o.AssignedID
}

func (o *CreateTrackerEntryRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateTrackerEntryRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTrackerEntryRequest) GetDuration() float64 {
	if o == nil {
		return 0.0
	}
	return o.Duration
}

// CreateTrackerEntryUser - User information for the person who created this tracker entry
type CreateTrackerEntryUser struct {
	// Unique identifier of the user
	ID string `json:"id"`
	// Full name of the user
	FullName string `json:"fullName"`
	// URL to the user's avatar image
	AvatarURL string `json:"avatarUrl"`
}

func (o *CreateTrackerEntryUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateTrackerEntryUser) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *CreateTrackerEntryUser) GetAvatarURL() string {
	if o == nil {
		return ""
	}
	return o.AvatarURL
}

// CreateTrackerEntryCustomer - Customer information associated with the project
type CreateTrackerEntryCustomer struct {
	// Unique identifier of the customer
	ID string `json:"id"`
	// Name of the customer or organization
	Name string `json:"name"`
}

func (o *CreateTrackerEntryCustomer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateTrackerEntryCustomer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// CreateTrackerEntryProject - Project information associated with this tracker entry
type CreateTrackerEntryProject struct {
	// Unique identifier of the project
	ID string `json:"id"`
	// Date and time when the project was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Default hourly rate for the project
	Rate *float64 `json:"rate"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Current status of the project
	Status string `json:"status"`
	// Description of the project
	Description *string `json:"description"`
	// Name of the project
	Name string `json:"name"`
	// Whether the project is billable to the customer
	Billable *bool `json:"billable"`
	// Estimated total hours for the project
	Estimate *float64 `json:"estimate"`
	// Customer information associated with the project
	Customer *CreateTrackerEntryCustomer `json:"customer"`
}

func (o *CreateTrackerEntryProject) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateTrackerEntryProject) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *CreateTrackerEntryProject) GetRate() *float64 {
	if o == nil {
		return nil
	}
	return o.Rate
}

func (o *CreateTrackerEntryProject) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateTrackerEntryProject) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *CreateTrackerEntryProject) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTrackerEntryProject) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateTrackerEntryProject) GetBillable() *bool {
	if o == nil {
		return nil
	}
	return o.Billable
}

func (o *CreateTrackerEntryProject) GetEstimate() *float64 {
	if o == nil {
		return nil
	}
	return o.Estimate
}

func (o *CreateTrackerEntryProject) GetCustomer() *CreateTrackerEntryCustomer {
	if o == nil {
		return nil
	}
	return o.Customer
}

type CreateTrackerEntryData struct {
	// Unique identifier of the tracker entry
	ID string `json:"id"`
	// Date and time when the tracker entry was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Duration of the tracker entry in seconds
	Duration float64 `json:"duration"`
	// Start time of the tracker entry in ISO 8601 format
	Start string `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop string `json:"stop"`
	// Unique identifier of the team that owns this tracker entry
	TeamID string `json:"teamId"`
	// Description or notes for the tracker entry
	Description *string `json:"description"`
	// Hourly rate applied to this tracker entry
	Rate *float64 `json:"rate"`
	// Currency code for the rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Whether this tracker entry has been billed to the customer
	Billed bool `json:"billed"`
	// Date of the tracker entry in YYYY-MM-DD format
	Date string `json:"date"`
	// User information for the person who created this tracker entry
	User CreateTrackerEntryUser `json:"user"`
	// Project information associated with this tracker entry
	Project CreateTrackerEntryProject `json:"project"`
}

func (o *CreateTrackerEntryData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateTrackerEntryData) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *CreateTrackerEntryData) GetDuration() float64 {
	if o == nil {
		return 0.0
	}
	return o.Duration
}

func (o *CreateTrackerEntryData) GetStart() string {
	if o == nil {
		return ""
	}
	return o.Start
}

func (o *CreateTrackerEntryData) GetStop() string {
	if o == nil {
		return ""
	}
	return o.Stop
}

func (o *CreateTrackerEntryData) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *CreateTrackerEntryData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTrackerEntryData) GetRate() *float64 {
	if o == nil {
		return nil
	}
	return o.Rate
}

func (o *CreateTrackerEntryData) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateTrackerEntryData) GetBilled() bool {
	if o == nil {
		return false
	}
	return o.Billed
}

func (o *CreateTrackerEntryData) GetDate() string {
	if o == nil {
		return ""
	}
	return o.Date
}

func (o *CreateTrackerEntryData) GetUser() CreateTrackerEntryUser {
	if o == nil {
		return CreateTrackerEntryUser{}
	}
	return o.User
}

func (o *CreateTrackerEntryData) GetProject() CreateTrackerEntryProject {
	if o == nil {
		return CreateTrackerEntryProject{}
	}
	return o.Project
}

// CreateTrackerEntryResponseBody - Response schema for created tracker entries
type CreateTrackerEntryResponseBody struct {
	// Array of created tracker entries
	Data []CreateTrackerEntryData `json:"data"`
}

func (o *CreateTrackerEntryResponseBody) GetData() []CreateTrackerEntryData {
	if o == nil {
		return []CreateTrackerEntryData{}
	}
	return o.Data
}

type CreateTrackerEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker entry created successfully.
	Object *CreateTrackerEntryResponseBody
}

func (o *CreateTrackerEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTrackerEntryResponse) GetObject() *CreateTrackerEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
