// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
)

// CreateTrackerProjectStatus - Current status of the project
type CreateTrackerProjectStatus string

const (
	CreateTrackerProjectStatusInProgress CreateTrackerProjectStatus = "in_progress"
	CreateTrackerProjectStatusCompleted  CreateTrackerProjectStatus = "completed"
)

func (e CreateTrackerProjectStatus) ToPointer() *CreateTrackerProjectStatus {
	return &e
}
func (e *CreateTrackerProjectStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_progress":
		fallthrough
	case "completed":
		*e = CreateTrackerProjectStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateTrackerProjectStatus: %v", v)
	}
}

type CreateTrackerProjectTag struct {
	// Unique identifier of the tag
	ID string `json:"id"`
	// Display value of the tag
	Value string `json:"value"`
}

func (o *CreateTrackerProjectTag) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateTrackerProjectTag) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

// CreateTrackerProjectRequest - Tracker project to create
type CreateTrackerProjectRequest struct {
	// Name of the project
	Name string `json:"name"`
	// Detailed description of the project
	Description *string `json:"description,omitempty"`
	// Estimated total hours required to complete the project
	Estimate *float64 `json:"estimate,omitempty"`
	// Whether the project is billable to the customer
	Billable *bool `default:"false" json:"billable"`
	// Hourly rate for the project in the specified currency
	Rate *float64 `json:"rate,omitempty"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency,omitempty"`
	// Current status of the project
	Status *CreateTrackerProjectStatus `json:"status,omitempty"`
	// Unique identifier of the customer associated with this project
	CustomerID *string `json:"customerId,omitempty"`
	// Array of tags to associate with the project
	Tags []CreateTrackerProjectTag `json:"tags,omitempty"`
}

func (c CreateTrackerProjectRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTrackerProjectRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateTrackerProjectRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateTrackerProjectRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTrackerProjectRequest) GetEstimate() *float64 {
	if o == nil {
		return nil
	}
	return o.Estimate
}

func (o *CreateTrackerProjectRequest) GetBillable() *bool {
	if o == nil {
		return nil
	}
	return o.Billable
}

func (o *CreateTrackerProjectRequest) GetRate() *float64 {
	if o == nil {
		return nil
	}
	return o.Rate
}

func (o *CreateTrackerProjectRequest) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateTrackerProjectRequest) GetStatus() *CreateTrackerProjectStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateTrackerProjectRequest) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *CreateTrackerProjectRequest) GetTags() []CreateTrackerProjectTag {
	if o == nil {
		return nil
	}
	return o.Tags
}

type CreateTrackerProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker project created successfully.
	TrackerProjectResponse *components.TrackerProjectResponse
}

func (o *CreateTrackerProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTrackerProjectResponse) GetTrackerProjectResponse() *components.TrackerProjectResponse {
	if o == nil {
		return nil
	}
	return o.TrackerProjectResponse
}
