// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type CreateInvoicePaymentIntentRequest struct {
	// Invoice token for authentication
	Token string `json:"token"`
}

func (o *CreateInvoicePaymentIntentRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

// CreateInvoicePaymentIntentResponseBody - Payment intent created
type CreateInvoicePaymentIntentResponseBody struct {
	ClientSecret    string  `json:"clientSecret"`
	Amount          float64 `json:"amount"`
	Currency        string  `json:"currency"`
	StripeAccountID string  `json:"stripeAccountId"`
}

func (o *CreateInvoicePaymentIntentResponseBody) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *CreateInvoicePaymentIntentResponseBody) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *CreateInvoicePaymentIntentResponseBody) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *CreateInvoicePaymentIntentResponseBody) GetStripeAccountID() string {
	if o == nil {
		return ""
	}
	return o.StripeAccountID
}

type CreateInvoicePaymentIntentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Payment intent created
	Object *CreateInvoicePaymentIntentResponseBody
}

func (o *CreateInvoicePaymentIntentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateInvoicePaymentIntentResponse) GetObject() *CreateInvoicePaymentIntentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
