// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

type Entry struct {
	// Start time of the tracker entry in ISO 8601 format
	Start time.Time `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop time.Time `json:"stop"`
	// Array of dates for which to create tracker entries
	Dates []string `json:"dates"`
	// Unique identifier of the user assigned to this tracker entry. If not provided, will use the authenticated user
	AssignedID *string `json:"assignedId,omitempty"`
	// Unique identifier of the project associated with this tracker entry
	ProjectID string `json:"projectId"`
	// Optional description or notes for the tracker entry
	Description *string `json:"description,omitempty"`
	// Duration of the tracker entry in seconds
	Duration float64 `json:"duration"`
}

func (e Entry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"start", "stop", "dates", "projectId", "duration"}); err != nil {
		return err
	}
	return nil
}

func (e *Entry) GetStart() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.Start
}

func (e *Entry) GetStop() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.Stop
}

func (e *Entry) GetDates() []string {
	if e == nil {
		return []string{}
	}
	return e.Dates
}

func (e *Entry) GetAssignedID() *string {
	if e == nil {
		return nil
	}
	return e.AssignedID
}

func (e *Entry) GetProjectID() string {
	if e == nil {
		return ""
	}
	return e.ProjectID
}

func (e *Entry) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *Entry) GetDuration() float64 {
	if e == nil {
		return 0.0
	}
	return e.Duration
}

type CreateTrackerEntriesBulkRequest struct {
	// Array of tracker entries to create (maximum 100 entries per request)
	Entries []Entry `json:"entries"`
}

func (c *CreateTrackerEntriesBulkRequest) GetEntries() []Entry {
	if c == nil {
		return []Entry{}
	}
	return c.Entries
}

// CreateTrackerEntriesBulkUser - User information for the person who created this tracker entry
type CreateTrackerEntriesBulkUser struct {
	// Unique identifier of the user
	ID string `json:"id"`
	// Full name of the user
	FullName string `json:"fullName"`
	// URL to the user's avatar image
	AvatarURL string `json:"avatarUrl"`
}

func (c *CreateTrackerEntriesBulkUser) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateTrackerEntriesBulkUser) GetFullName() string {
	if c == nil {
		return ""
	}
	return c.FullName
}

func (c *CreateTrackerEntriesBulkUser) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

// CreateTrackerEntriesBulkCustomer - Customer information associated with the project
type CreateTrackerEntriesBulkCustomer struct {
	// Unique identifier of the customer
	ID string `json:"id"`
	// Name of the customer or organization
	Name string `json:"name"`
}

func (c *CreateTrackerEntriesBulkCustomer) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateTrackerEntriesBulkCustomer) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

// CreateTrackerEntriesBulkProject - Project information associated with this tracker entry
type CreateTrackerEntriesBulkProject struct {
	// Unique identifier of the project
	ID string `json:"id"`
	// Date and time when the project was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Default hourly rate for the project
	Rate *float64 `json:"rate"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Current status of the project
	Status string `json:"status"`
	// Description of the project
	Description *string `json:"description"`
	// Name of the project
	Name string `json:"name"`
	// Whether the project is billable to the customer
	Billable *bool `json:"billable"`
	// Estimated total hours for the project
	Estimate *float64 `json:"estimate"`
	// Customer information associated with the project
	Customer *CreateTrackerEntriesBulkCustomer `json:"customer"`
}

func (c *CreateTrackerEntriesBulkProject) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateTrackerEntriesBulkProject) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateTrackerEntriesBulkProject) GetRate() *float64 {
	if c == nil {
		return nil
	}
	return c.Rate
}

func (c *CreateTrackerEntriesBulkProject) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateTrackerEntriesBulkProject) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateTrackerEntriesBulkProject) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateTrackerEntriesBulkProject) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTrackerEntriesBulkProject) GetBillable() *bool {
	if c == nil {
		return nil
	}
	return c.Billable
}

func (c *CreateTrackerEntriesBulkProject) GetEstimate() *float64 {
	if c == nil {
		return nil
	}
	return c.Estimate
}

func (c *CreateTrackerEntriesBulkProject) GetCustomer() *CreateTrackerEntriesBulkCustomer {
	if c == nil {
		return nil
	}
	return c.Customer
}

type CreateTrackerEntriesBulkData struct {
	// Unique identifier of the tracker entry
	ID string `json:"id"`
	// Date and time when the tracker entry was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Duration of the tracker entry in seconds
	Duration float64 `json:"duration"`
	// Start time of the tracker entry in ISO 8601 format
	Start string `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop string `json:"stop"`
	// Unique identifier of the team that owns this tracker entry
	TeamID string `json:"teamId"`
	// Description or notes for the tracker entry
	Description *string `json:"description"`
	// Hourly rate applied to this tracker entry
	Rate *float64 `json:"rate"`
	// Currency code for the rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Whether this tracker entry has been billed to the customer
	Billed bool `json:"billed"`
	// Date of the tracker entry in YYYY-MM-DD format
	Date string `json:"date"`
	// User information for the person who created this tracker entry
	User CreateTrackerEntriesBulkUser `json:"user"`
	// Project information associated with this tracker entry
	Project CreateTrackerEntriesBulkProject `json:"project"`
}

func (c *CreateTrackerEntriesBulkData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateTrackerEntriesBulkData) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateTrackerEntriesBulkData) GetDuration() float64 {
	if c == nil {
		return 0.0
	}
	return c.Duration
}

func (c *CreateTrackerEntriesBulkData) GetStart() string {
	if c == nil {
		return ""
	}
	return c.Start
}

func (c *CreateTrackerEntriesBulkData) GetStop() string {
	if c == nil {
		return ""
	}
	return c.Stop
}

func (c *CreateTrackerEntriesBulkData) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateTrackerEntriesBulkData) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateTrackerEntriesBulkData) GetRate() *float64 {
	if c == nil {
		return nil
	}
	return c.Rate
}

func (c *CreateTrackerEntriesBulkData) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateTrackerEntriesBulkData) GetBilled() bool {
	if c == nil {
		return false
	}
	return c.Billed
}

func (c *CreateTrackerEntriesBulkData) GetDate() string {
	if c == nil {
		return ""
	}
	return c.Date
}

func (c *CreateTrackerEntriesBulkData) GetUser() CreateTrackerEntriesBulkUser {
	if c == nil {
		return CreateTrackerEntriesBulkUser{}
	}
	return c.User
}

func (c *CreateTrackerEntriesBulkData) GetProject() CreateTrackerEntriesBulkProject {
	if c == nil {
		return CreateTrackerEntriesBulkProject{}
	}
	return c.Project
}

// CreateTrackerEntriesBulkResponseBody - Response schema for created tracker entries
type CreateTrackerEntriesBulkResponseBody struct {
	// Array of created tracker entries
	Data []CreateTrackerEntriesBulkData `json:"data"`
}

func (c *CreateTrackerEntriesBulkResponseBody) GetData() []CreateTrackerEntriesBulkData {
	if c == nil {
		return []CreateTrackerEntriesBulkData{}
	}
	return c.Data
}

type CreateTrackerEntriesBulkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker entries created successfully.
	Object *CreateTrackerEntriesBulkResponseBody
}

func (c *CreateTrackerEntriesBulkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTrackerEntriesBulkResponse) GetObject() *CreateTrackerEntriesBulkResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
