// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type CreateTagResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tag created
	TagsResponse *components.TagsResponse
}

func (o *CreateTagResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTagResponse) GetTagsResponse() *components.TagsResponse {
	if o == nil {
		return nil
	}
	return o.TagsResponse
}
