// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type CreateTransactionAttachment struct {
	// Path(s) of the attachment file(s).
	Path []string `json:"path"`
	// Name of the attachment file.
	Name string `json:"name"`
	// Size of the attachment file in bytes.
	Size float64 `json:"size"`
	// MIME type of the attachment file.
	Type string `json:"type"`
}

func (c *CreateTransactionAttachment) GetPath() []string {
	if c == nil {
		return []string{}
	}
	return c.Path
}

func (c *CreateTransactionAttachment) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTransactionAttachment) GetSize() float64 {
	if c == nil {
		return 0.0
	}
	return c.Size
}

func (c *CreateTransactionAttachment) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

type CreateTransactionRequest struct {
	// Name of the transaction.
	Name string `json:"name"`
	// Amount of the transaction.
	Amount float64 `json:"amount"`
	// Currency of the transaction.
	Currency string `json:"currency"`
	// Date of the transaction (ISO 8601).
	Date string `json:"date"`
	// Bank account ID associated with the transaction.
	BankAccountID string `json:"bankAccountId"`
	// Assigned user ID for the transaction.
	AssignedID *string `json:"assignedId,omitempty"`
	// Category slug for the transaction.
	CategorySlug *string `json:"categorySlug,omitempty"`
	// Note for the transaction.
	Note *string `json:"note,omitempty"`
	// Whether the transaction is internal.
	Internal *bool `json:"internal,omitempty"`
	// Array of attachments for the transaction.
	Attachments []CreateTransactionAttachment `json:"attachments,omitempty"`
}

func (c *CreateTransactionRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTransactionRequest) GetAmount() float64 {
	if c == nil {
		return 0.0
	}
	return c.Amount
}

func (c *CreateTransactionRequest) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CreateTransactionRequest) GetDate() string {
	if c == nil {
		return ""
	}
	return c.Date
}

func (c *CreateTransactionRequest) GetBankAccountID() string {
	if c == nil {
		return ""
	}
	return c.BankAccountID
}

func (c *CreateTransactionRequest) GetAssignedID() *string {
	if c == nil {
		return nil
	}
	return c.AssignedID
}

func (c *CreateTransactionRequest) GetCategorySlug() *string {
	if c == nil {
		return nil
	}
	return c.CategorySlug
}

func (c *CreateTransactionRequest) GetNote() *string {
	if c == nil {
		return nil
	}
	return c.Note
}

func (c *CreateTransactionRequest) GetInternal() *bool {
	if c == nil {
		return nil
	}
	return c.Internal
}

func (c *CreateTransactionRequest) GetAttachments() []CreateTransactionAttachment {
	if c == nil {
		return nil
	}
	return c.Attachments
}

type CreateTransactionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Transaction created
	TransactionResponse *components.TransactionResponse
}

func (c *CreateTransactionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTransactionResponse) GetTransactionResponse() *components.TransactionResponse {
	if c == nil {
		return nil
	}
	return c.TransactionResponse
}
