// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type DeleteInboxItemRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteInboxItemRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteInboxItemResponseBody - Response schema for a successfully deleted inbox item.
type DeleteInboxItemResponseBody struct {
	// The unique identifier of the deleted inbox item.
	ID string `json:"id"`
}

func (d *DeleteInboxItemResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteInboxItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete a inbox item by its ID.
	Object *DeleteInboxItemResponseBody
}

func (d *DeleteInboxItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteInboxItemResponse) GetObject() *DeleteInboxItemResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
