// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type DeleteTrackerProjectRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteTrackerProjectRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteTrackerProjectResponseBody - Tracker project deleted successfully.
type DeleteTrackerProjectResponseBody struct {
	// Unique identifier of the project to delete
	ID string `json:"id"`
}

func (d *DeleteTrackerProjectResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteTrackerProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker project deleted successfully.
	Object *DeleteTrackerProjectResponseBody
}

func (d *DeleteTrackerProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteTrackerProjectResponse) GetObject() *DeleteTrackerProjectResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
