// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type DeleteInvoiceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteInvoiceRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteInvoiceResponseBody - Delete a invoice by its unique identifier for the authenticated team.
type DeleteInvoiceResponseBody struct {
	// Unique identifier for the deleted invoice
	ID string `json:"id"`
}

func (d *DeleteInvoiceResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete a invoice by its unique identifier for the authenticated team.
	Object *DeleteInvoiceResponseBody
}

func (d *DeleteInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteInvoiceResponse) GetObject() *DeleteInvoiceResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
