// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type DeleteInboxItemRequest struct {
	// The unique identifier of the inbox item to delete.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteInboxItemRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteInboxItemResponseBody - Response schema for a successfully deleted inbox item.
type DeleteInboxItemResponseBody struct {
	// The unique identifier of the deleted inbox item.
	ID string `json:"id"`
}

func (o *DeleteInboxItemResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteInboxItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete a inbox item by its ID.
	Object *DeleteInboxItemResponseBody
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *DeleteInboxItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteInboxItemResponse) GetObject() *DeleteInboxItemResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteInboxItemResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
