// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type DeleteDocumentRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDocumentRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteDocumentResponseBody - Document deleted successfully
type DeleteDocumentResponseBody struct {
	ID string `json:"id"`
}

func (o *DeleteDocumentResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteDocumentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Document deleted successfully
	Object *DeleteDocumentResponseBody
}

func (o *DeleteDocumentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteDocumentResponse) GetObject() *DeleteDocumentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
