// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type FortnoxOAuthCallbackRequest struct {
	// OAuth authorization code from Fortnox
	Code *string `queryParam:"style=form,explode=true,name=code"`
	// OAuth state parameter for CSRF protection
	State string `queryParam:"style=form,explode=true,name=state"`
	// OAuth error code if authorization failed
	Error *string `queryParam:"style=form,explode=true,name=error"`
}

func (o *FortnoxOAuthCallbackRequest) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *FortnoxOAuthCallbackRequest) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}

func (o *FortnoxOAuthCallbackRequest) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type FortnoxOAuthCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *FortnoxOAuthCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *FortnoxOAuthCallbackResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
