// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetBankAccountByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetBankAccountByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetBankAccountByIDResponseBody - A single bank account object response.
type GetBankAccountByIDResponseBody struct {
	// Unique identifier for the bank account.
	ID string `json:"id"`
	// Name of the bank account.
	Name *string `json:"name"`
	// Currency code of the bank account (e.g., USD, EUR).
	Currency *string `json:"currency"`
	// Type of the bank account (e.g., depository, credit).
	Type *string `json:"type"`
	// Whether the bank account is enabled.
	Enabled bool `json:"enabled"`
	// Current balance of the bank account.
	Balance *float64 `json:"balance"`
	// Whether the bank account is a manual account.
	Manual *bool `json:"manual"`
}

func (o *GetBankAccountByIDResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetBankAccountByIDResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetBankAccountByIDResponseBody) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *GetBankAccountByIDResponseBody) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *GetBankAccountByIDResponseBody) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *GetBankAccountByIDResponseBody) GetBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *GetBankAccountByIDResponseBody) GetManual() *bool {
	if o == nil {
		return nil
	}
	return o.Manual
}

type GetBankAccountByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bank account details
	Object *GetBankAccountByIDResponseBody
}

func (o *GetBankAccountByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBankAccountByIDResponse) GetObject() *GetBankAccountByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
