// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetBurnRateReportsRequest struct {
	// Start date (ISO 8601 format)
	From string `queryParam:"style=form,explode=true,name=from"`
	// End date (ISO 8601 format)
	To string `queryParam:"style=form,explode=true,name=to"`
	// Currency code (ISO 4217)
	Currency *string `queryParam:"style=form,explode=true,name=currency"`
}

func (o *GetBurnRateReportsRequest) GetFrom() string {
	if o == nil {
		return ""
	}
	return o.From
}

func (o *GetBurnRateReportsRequest) GetTo() string {
	if o == nil {
		return ""
	}
	return o.To
}

func (o *GetBurnRateReportsRequest) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

type GetBurnRateReportsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Burn rate reports for the authenticated team.
	GetBurnRateResponseSchema []components.BurnRateItem
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *GetBurnRateReportsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBurnRateReportsResponse) GetGetBurnRateResponseSchema() []components.BurnRateItem {
	if o == nil {
		return nil
	}
	return o.GetBurnRateResponseSchema
}

func (o *GetBurnRateReportsResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
