// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetCurrentTimerRequest struct {
	AssignedID *string `queryParam:"style=form,explode=true,name=assignedId"`
}

func (g *GetCurrentTimerRequest) GetAssignedID() *string {
	if g == nil {
		return nil
	}
	return g.AssignedID
}

// GetCurrentTimerUser - User information for the person who created this tracker entry
type GetCurrentTimerUser struct {
	// Unique identifier of the user
	ID string `json:"id"`
	// Full name of the user
	FullName string `json:"fullName"`
	// URL to the user's avatar image
	AvatarURL string `json:"avatarUrl"`
}

func (g *GetCurrentTimerUser) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCurrentTimerUser) GetFullName() string {
	if g == nil {
		return ""
	}
	return g.FullName
}

func (g *GetCurrentTimerUser) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

// GetCurrentTimerCustomer - Customer information associated with the project
type GetCurrentTimerCustomer struct {
	// Unique identifier of the customer
	ID string `json:"id"`
	// Name of the customer or organization
	Name string `json:"name"`
}

func (g *GetCurrentTimerCustomer) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCurrentTimerCustomer) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

// GetCurrentTimerProject - Project information associated with this tracker entry
type GetCurrentTimerProject struct {
	// Unique identifier of the project
	ID string `json:"id"`
	// Date and time when the project was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Default hourly rate for the project
	Rate *float64 `json:"rate"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Current status of the project
	Status string `json:"status"`
	// Description of the project
	Description *string `json:"description"`
	// Name of the project
	Name string `json:"name"`
	// Whether the project is billable to the customer
	Billable *bool `json:"billable"`
	// Estimated total hours for the project
	Estimate *float64 `json:"estimate"`
	// Customer information associated with the project
	Customer *GetCurrentTimerCustomer `json:"customer"`
}

func (g *GetCurrentTimerProject) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCurrentTimerProject) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetCurrentTimerProject) GetRate() *float64 {
	if g == nil {
		return nil
	}
	return g.Rate
}

func (g *GetCurrentTimerProject) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GetCurrentTimerProject) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetCurrentTimerProject) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetCurrentTimerProject) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetCurrentTimerProject) GetBillable() *bool {
	if g == nil {
		return nil
	}
	return g.Billable
}

func (g *GetCurrentTimerProject) GetEstimate() *float64 {
	if g == nil {
		return nil
	}
	return g.Estimate
}

func (g *GetCurrentTimerProject) GetCustomer() *GetCurrentTimerCustomer {
	if g == nil {
		return nil
	}
	return g.Customer
}

type GetCurrentTimerData struct {
	// Unique identifier of the tracker entry
	ID string `json:"id"`
	// Date and time when the tracker entry was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Duration of the timer entry in seconds. -1 indicates running, null for paused, positive number for completed
	Duration *float64 `json:"duration"`
	// Start time of the tracker entry in ISO 8601 format
	Start string `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop string `json:"stop"`
	// Unique identifier of the team that owns this tracker entry
	TeamID string `json:"teamId"`
	// Description or notes for the tracker entry
	Description *string `json:"description"`
	// Hourly rate applied to this tracker entry
	Rate *float64 `json:"rate"`
	// Currency code for the rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Whether this tracker entry has been billed to the customer
	Billed bool `json:"billed"`
	// Date of the tracker entry in YYYY-MM-DD format
	Date string `json:"date"`
	// User information for the person who created this tracker entry
	User GetCurrentTimerUser `json:"user"`
	// Project information associated with this tracker entry
	Project GetCurrentTimerProject `json:"project"`
}

func (g *GetCurrentTimerData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCurrentTimerData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetCurrentTimerData) GetDuration() *float64 {
	if g == nil {
		return nil
	}
	return g.Duration
}

func (g *GetCurrentTimerData) GetStart() string {
	if g == nil {
		return ""
	}
	return g.Start
}

func (g *GetCurrentTimerData) GetStop() string {
	if g == nil {
		return ""
	}
	return g.Stop
}

func (g *GetCurrentTimerData) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetCurrentTimerData) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetCurrentTimerData) GetRate() *float64 {
	if g == nil {
		return nil
	}
	return g.Rate
}

func (g *GetCurrentTimerData) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GetCurrentTimerData) GetBilled() bool {
	if g == nil {
		return false
	}
	return g.Billed
}

func (g *GetCurrentTimerData) GetDate() string {
	if g == nil {
		return ""
	}
	return g.Date
}

func (g *GetCurrentTimerData) GetUser() GetCurrentTimerUser {
	if g == nil {
		return GetCurrentTimerUser{}
	}
	return g.User
}

func (g *GetCurrentTimerData) GetProject() GetCurrentTimerProject {
	if g == nil {
		return GetCurrentTimerProject{}
	}
	return g.Project
}

// GetCurrentTimerResponseBody - Current timer retrieved successfully.
type GetCurrentTimerResponseBody struct {
	Data *GetCurrentTimerData `json:"data"`
}

func (g *GetCurrentTimerResponseBody) GetData() *GetCurrentTimerData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetCurrentTimerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current timer retrieved successfully.
	Object *GetCurrentTimerResponseBody
}

func (g *GetCurrentTimerResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCurrentTimerResponse) GetObject() *GetCurrentTimerResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
