// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetCustomerByIDRequest struct {
	// Unique identifier of the customer to retrieve
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCustomerByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetCustomerByIDTag struct {
	// Unique identifier of the tag
	ID string `json:"id"`
	// Display name of the tag
	Name string `json:"name"`
}

func (o *GetCustomerByIDTag) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerByIDTag) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// GetCustomerByIDResponseBody - Retrieve a customer by ID for the authenticated team.
type GetCustomerByIDResponseBody struct {
	// Unique identifier of the customer
	ID string `json:"id"`
	// Name of the customer or organization
	Name string `json:"name"`
	// Primary email address of the customer
	Email string `json:"email"`
	// Billing email addresses of the customer (comma-separated for multiple)
	BillingEmail *string `json:"billingEmail"`
	// Primary phone number of the customer
	Phone *string `json:"phone"`
	// Website URL of the customer
	Website *string `json:"website"`
	// Date and time when the customer was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Country name where the customer is located
	Country *string `json:"country"`
	// First line of the customer's address
	AddressLine1 *string `json:"addressLine1"`
	// Second line of the customer's address (suite, apartment, etc.)
	AddressLine2 *string `json:"addressLine2"`
	// City where the customer is located
	City *string `json:"city"`
	// State or province where the customer is located
	State *string `json:"state"`
	// ZIP or postal code of the customer's address
	Zip *string `json:"zip"`
	// Internal notes about the customer for team reference
	Note *string `json:"note"`
	// VAT (Value Added Tax) number of the customer
	VatNumber *string `json:"vatNumber"`
	// Country code in ISO 3166-1 alpha-2 format
	CountryCode *string `json:"countryCode"`
	// Unique token for the customer (used for internal identification)
	Token string `json:"token"`
	// Primary contact person's name at the customer organization
	Contact *string `json:"contact"`
	// Total number of invoices created for this customer
	InvoiceCount float64 `json:"invoiceCount"`
	// Total number of projects associated with this customer
	ProjectCount float64 `json:"projectCount"`
	// Total revenue from paid invoices for this customer (in invoice currency). Only returned in list queries.
	TotalRevenue *float64 `json:"totalRevenue,omitempty"`
	// Total outstanding amount from unpaid/overdue invoices (in invoice currency). Only returned in list queries.
	OutstandingAmount *float64 `json:"outstandingAmount,omitempty"`
	// Date of the most recent invoice in ISO 8601 format. Only returned in list queries.
	LastInvoiceDate *string `json:"lastInvoiceDate,omitempty"`
	// Primary currency used in invoices for this customer. Only returned in list queries.
	InvoiceCurrency *string `json:"invoiceCurrency,omitempty"`
	// Array of tags associated with the customer for categorization
	Tags []GetCustomerByIDTag `json:"tags"`
	// AI-generated description of what the company does
	Description *string `json:"description"`
	// Primary industry of the company
	Industry *string `json:"industry"`
	// Business model type
	CompanyType *string `json:"companyType"`
	// Estimated number of employees
	EmployeeCount *string `json:"employeeCount"`
	// Year the company was founded
	FoundedYear *float64 `json:"foundedYear"`
	// Estimated annual revenue range
	EstimatedRevenue *string `json:"estimatedRevenue"`
	// Current funding stage
	FundingStage *string `json:"fundingStage"`
	// Total funding raised
	TotalFunding *string `json:"totalFunding"`
	// Company headquarters location
	HeadquartersLocation *string `json:"headquartersLocation"`
	// IANA timezone of the company headquarters
	Timezone *string `json:"timezone"`
	// LinkedIn company page URL
	LinkedinURL *string `json:"linkedinUrl"`
	// Twitter/X profile URL
	TwitterURL *string `json:"twitterUrl"`
	// Instagram profile URL
	InstagramURL *string `json:"instagramUrl"`
	// Facebook page URL
	FacebookURL *string `json:"facebookUrl"`
	// URL to the company logo
	LogoURL *string `json:"logoUrl"`
	// Name of the CEO or founder
	CeoName *string `json:"ceoName"`
	// Name of the finance/AP contact for invoicing
	FinanceContact *string `json:"financeContact"`
	// Email of the finance/AP contact
	FinanceContactEmail *string `json:"financeContactEmail"`
	// Primary business language (ISO 639-1 code)
	PrimaryLanguage *string `json:"primaryLanguage"`
	// Month when the fiscal year ends
	FiscalYearEnd *string `json:"fiscalYearEnd"`
	// Status of the enrichment process
	EnrichmentStatus *string `json:"enrichmentStatus"`
	// When the customer was last enriched
	EnrichedAt *string `json:"enrichedAt"`
}

func (o *GetCustomerByIDResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerByIDResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetCustomerByIDResponseBody) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *GetCustomerByIDResponseBody) GetBillingEmail() *string {
	if o == nil {
		return nil
	}
	return o.BillingEmail
}

func (o *GetCustomerByIDResponseBody) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *GetCustomerByIDResponseBody) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}

func (o *GetCustomerByIDResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *GetCustomerByIDResponseBody) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *GetCustomerByIDResponseBody) GetAddressLine1() *string {
	if o == nil {
		return nil
	}
	return o.AddressLine1
}

func (o *GetCustomerByIDResponseBody) GetAddressLine2() *string {
	if o == nil {
		return nil
	}
	return o.AddressLine2
}

func (o *GetCustomerByIDResponseBody) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *GetCustomerByIDResponseBody) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *GetCustomerByIDResponseBody) GetZip() *string {
	if o == nil {
		return nil
	}
	return o.Zip
}

func (o *GetCustomerByIDResponseBody) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}

func (o *GetCustomerByIDResponseBody) GetVatNumber() *string {
	if o == nil {
		return nil
	}
	return o.VatNumber
}

func (o *GetCustomerByIDResponseBody) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *GetCustomerByIDResponseBody) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *GetCustomerByIDResponseBody) GetContact() *string {
	if o == nil {
		return nil
	}
	return o.Contact
}

func (o *GetCustomerByIDResponseBody) GetInvoiceCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.InvoiceCount
}

func (o *GetCustomerByIDResponseBody) GetProjectCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.ProjectCount
}

func (o *GetCustomerByIDResponseBody) GetTotalRevenue() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalRevenue
}

func (o *GetCustomerByIDResponseBody) GetOutstandingAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.OutstandingAmount
}

func (o *GetCustomerByIDResponseBody) GetLastInvoiceDate() *string {
	if o == nil {
		return nil
	}
	return o.LastInvoiceDate
}

func (o *GetCustomerByIDResponseBody) GetInvoiceCurrency() *string {
	if o == nil {
		return nil
	}
	return o.InvoiceCurrency
}

func (o *GetCustomerByIDResponseBody) GetTags() []GetCustomerByIDTag {
	if o == nil {
		return []GetCustomerByIDTag{}
	}
	return o.Tags
}

func (o *GetCustomerByIDResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetCustomerByIDResponseBody) GetIndustry() *string {
	if o == nil {
		return nil
	}
	return o.Industry
}

func (o *GetCustomerByIDResponseBody) GetCompanyType() *string {
	if o == nil {
		return nil
	}
	return o.CompanyType
}

func (o *GetCustomerByIDResponseBody) GetEmployeeCount() *string {
	if o == nil {
		return nil
	}
	return o.EmployeeCount
}

func (o *GetCustomerByIDResponseBody) GetFoundedYear() *float64 {
	if o == nil {
		return nil
	}
	return o.FoundedYear
}

func (o *GetCustomerByIDResponseBody) GetEstimatedRevenue() *string {
	if o == nil {
		return nil
	}
	return o.EstimatedRevenue
}

func (o *GetCustomerByIDResponseBody) GetFundingStage() *string {
	if o == nil {
		return nil
	}
	return o.FundingStage
}

func (o *GetCustomerByIDResponseBody) GetTotalFunding() *string {
	if o == nil {
		return nil
	}
	return o.TotalFunding
}

func (o *GetCustomerByIDResponseBody) GetHeadquartersLocation() *string {
	if o == nil {
		return nil
	}
	return o.HeadquartersLocation
}

func (o *GetCustomerByIDResponseBody) GetTimezone() *string {
	if o == nil {
		return nil
	}
	return o.Timezone
}

func (o *GetCustomerByIDResponseBody) GetLinkedinURL() *string {
	if o == nil {
		return nil
	}
	return o.LinkedinURL
}

func (o *GetCustomerByIDResponseBody) GetTwitterURL() *string {
	if o == nil {
		return nil
	}
	return o.TwitterURL
}

func (o *GetCustomerByIDResponseBody) GetInstagramURL() *string {
	if o == nil {
		return nil
	}
	return o.InstagramURL
}

func (o *GetCustomerByIDResponseBody) GetFacebookURL() *string {
	if o == nil {
		return nil
	}
	return o.FacebookURL
}

func (o *GetCustomerByIDResponseBody) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *GetCustomerByIDResponseBody) GetCeoName() *string {
	if o == nil {
		return nil
	}
	return o.CeoName
}

func (o *GetCustomerByIDResponseBody) GetFinanceContact() *string {
	if o == nil {
		return nil
	}
	return o.FinanceContact
}

func (o *GetCustomerByIDResponseBody) GetFinanceContactEmail() *string {
	if o == nil {
		return nil
	}
	return o.FinanceContactEmail
}

func (o *GetCustomerByIDResponseBody) GetPrimaryLanguage() *string {
	if o == nil {
		return nil
	}
	return o.PrimaryLanguage
}

func (o *GetCustomerByIDResponseBody) GetFiscalYearEnd() *string {
	if o == nil {
		return nil
	}
	return o.FiscalYearEnd
}

func (o *GetCustomerByIDResponseBody) GetEnrichmentStatus() *string {
	if o == nil {
		return nil
	}
	return o.EnrichmentStatus
}

func (o *GetCustomerByIDResponseBody) GetEnrichedAt() *string {
	if o == nil {
		return nil
	}
	return o.EnrichedAt
}

type GetCustomerByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a customer by ID for the authenticated team.
	Object *GetCustomerByIDResponseBody
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *GetCustomerByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCustomerByIDResponse) GetObject() *GetCustomerByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetCustomerByIDResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
