// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

type GetDocumentPreSignedURLRequest struct {
	ID       string `pathParam:"style=simple,explode=false,name=id"`
	Download *bool  `queryParam:"style=form,explode=true,name=download"`
}

func (o *GetDocumentPreSignedURLRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetDocumentPreSignedURLRequest) GetDownload() *bool {
	if o == nil {
		return nil
	}
	return o.Download
}

// GetDocumentPreSignedURLResponseBody - Pre-signed URL generated successfully
type GetDocumentPreSignedURLResponseBody struct {
	// Pre-signed URL for accessing the document, valid for 60 seconds
	URL string `json:"url"`
	// ISO 8601 timestamp when the URL expires
	ExpiresAt time.Time `json:"expiresAt"`
	// Original filename of the document
	FileName *string `json:"fileName"`
}

func (g GetDocumentPreSignedURLResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDocumentPreSignedURLResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDocumentPreSignedURLResponseBody) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *GetDocumentPreSignedURLResponseBody) GetExpiresAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ExpiresAt
}

func (o *GetDocumentPreSignedURLResponseBody) GetFileName() *string {
	if o == nil {
		return nil
	}
	return o.FileName
}

type GetDocumentPreSignedURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Pre-signed URL generated successfully
	Object *GetDocumentPreSignedURLResponseBody
}

func (o *GetDocumentPreSignedURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDocumentPreSignedURLResponse) GetObject() *GetDocumentPreSignedURLResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
