// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetExpensesMetricsRequest struct {
	From     string  `queryParam:"style=form,explode=true,name=from"`
	To       string  `queryParam:"style=form,explode=true,name=to"`
	Currency *string `queryParam:"style=form,explode=true,name=currency"`
}

func (o *GetExpensesMetricsRequest) GetFrom() string {
	if o == nil {
		return ""
	}
	return o.From
}

func (o *GetExpensesMetricsRequest) GetTo() string {
	if o == nil {
		return ""
	}
	return o.To
}

func (o *GetExpensesMetricsRequest) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

type GetExpensesMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Expense metrics for the authenticated team.
	GetExpensesResponseSchema *components.GetExpensesResponseSchema
}

func (o *GetExpensesMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetExpensesMetricsResponse) GetGetExpensesResponseSchema() *components.GetExpensesResponseSchema {
	if o == nil {
		return nil
	}
	return o.GetExpensesResponseSchema
}
