// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// GetFortnoxInstallURLResponseBody - Fortnox install URL
type GetFortnoxInstallURLResponseBody struct {
	URL string `json:"url"`
}

func (o *GetFortnoxInstallURLResponseBody) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetFortnoxInstallURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Fortnox install URL
	Object *GetFortnoxInstallURLResponseBody
}

func (o *GetFortnoxInstallURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetFortnoxInstallURLResponse) GetObject() *GetFortnoxInstallURLResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
