// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetInboxItemByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetInboxItemByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetInboxItemByIDTransaction - Matched transaction for this inbox item, if any
type GetInboxItemByIDTransaction struct {
	// Transaction ID (UUID)
	ID string `json:"id"`
	// Transaction amount
	Amount float64 `json:"amount"`
	// Transaction currency (ISO 4217)
	Currency string `json:"currency"`
	// Transaction name or payee
	Name string `json:"name"`
	// Transaction date (ISO 8601)
	Date string `json:"date"`
}

func (g *GetInboxItemByIDTransaction) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetInboxItemByIDTransaction) GetAmount() float64 {
	if g == nil {
		return 0.0
	}
	return g.Amount
}

func (g *GetInboxItemByIDTransaction) GetCurrency() string {
	if g == nil {
		return ""
	}
	return g.Currency
}

func (g *GetInboxItemByIDTransaction) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetInboxItemByIDTransaction) GetDate() string {
	if g == nil {
		return ""
	}
	return g.Date
}

// GetInboxItemByIDResponseBody - Inbox item object
type GetInboxItemByIDResponseBody struct {
	// Inbox item ID (UUID)
	ID string `json:"id"`
	// Original file name of the uploaded document
	FileName string `json:"fileName"`
	// Path segments to the file in storage
	FilePath []string `json:"filePath"`
	// Display name for the inbox item
	DisplayName string `json:"displayName"`
	// Amount detected or entered for the inbox item
	Amount *float64 `json:"amount"`
	// Currency code (ISO 4217) for the amount
	Currency *string `json:"currency"`
	// MIME type of the uploaded file
	ContentType *string `json:"contentType"`
	// Date associated with the inbox item (ISO 8601)
	Date *string `json:"date"`
	// Status of the inbox item
	Status string `json:"status"`
	// Date and time when the inbox item was created (ISO 8601)
	CreatedAt string `json:"createdAt"`
	// Website associated with the inbox item, if any
	Website *string `json:"website"`
	// Description or notes for the inbox item
	Description *string `json:"description"`
	// Matched transaction for this inbox item, if any
	Transaction *GetInboxItemByIDTransaction `json:"transaction"`
}

func (g *GetInboxItemByIDResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetInboxItemByIDResponseBody) GetFileName() string {
	if g == nil {
		return ""
	}
	return g.FileName
}

func (g *GetInboxItemByIDResponseBody) GetFilePath() []string {
	if g == nil {
		return []string{}
	}
	return g.FilePath
}

func (g *GetInboxItemByIDResponseBody) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetInboxItemByIDResponseBody) GetAmount() *float64 {
	if g == nil {
		return nil
	}
	return g.Amount
}

func (g *GetInboxItemByIDResponseBody) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GetInboxItemByIDResponseBody) GetContentType() *string {
	if g == nil {
		return nil
	}
	return g.ContentType
}

func (g *GetInboxItemByIDResponseBody) GetDate() *string {
	if g == nil {
		return nil
	}
	return g.Date
}

func (g *GetInboxItemByIDResponseBody) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetInboxItemByIDResponseBody) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetInboxItemByIDResponseBody) GetWebsite() *string {
	if g == nil {
		return nil
	}
	return g.Website
}

func (g *GetInboxItemByIDResponseBody) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetInboxItemByIDResponseBody) GetTransaction() *GetInboxItemByIDTransaction {
	if g == nil {
		return nil
	}
	return g.Transaction
}

type GetInboxItemByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve an inbox item by its ID.
	Object *GetInboxItemByIDResponseBody
}

func (g *GetInboxItemByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInboxItemByIDResponse) GetObject() *GetInboxItemByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
