// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

// GetInvoiceSummaryStatus - Filter summary by invoice status
type GetInvoiceSummaryStatus string

const (
	GetInvoiceSummaryStatusDraft    GetInvoiceSummaryStatus = "draft"
	GetInvoiceSummaryStatusOverdue  GetInvoiceSummaryStatus = "overdue"
	GetInvoiceSummaryStatusPaid     GetInvoiceSummaryStatus = "paid"
	GetInvoiceSummaryStatusUnpaid   GetInvoiceSummaryStatus = "unpaid"
	GetInvoiceSummaryStatusCanceled GetInvoiceSummaryStatus = "canceled"
)

func (e GetInvoiceSummaryStatus) ToPointer() *GetInvoiceSummaryStatus {
	return &e
}
func (e *GetInvoiceSummaryStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "overdue":
		fallthrough
	case "paid":
		fallthrough
	case "unpaid":
		fallthrough
	case "canceled":
		*e = GetInvoiceSummaryStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetInvoiceSummaryStatus: %v", v)
	}
}

type GetInvoiceSummaryRequest struct {
	// Filter summary by invoice status
	Status *GetInvoiceSummaryStatus `queryParam:"style=form,explode=true,name=status"`
}

func (o *GetInvoiceSummaryRequest) GetStatus() *GetInvoiceSummaryStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetInvoiceSummaryResponseBody struct {
	// Currency of the invoice
	Currency string `json:"currency"`
	// Total amount of the invoice
	TotalAmount float64 `json:"totalAmount"`
	// Number of invoices for this currency
	InvoiceCount float64 `json:"invoiceCount"`
}

func (o *GetInvoiceSummaryResponseBody) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *GetInvoiceSummaryResponseBody) GetTotalAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.TotalAmount
}

func (o *GetInvoiceSummaryResponseBody) GetInvoiceCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.InvoiceCount
}

type GetInvoiceSummaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Summary of invoices for the authenticated team.
	ResponseBodies []GetInvoiceSummaryResponseBody
}

func (o *GetInvoiceSummaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInvoiceSummaryResponse) GetResponseBodies() []GetInvoiceSummaryResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
