// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

// ResponseType - OAuth response type, must be 'code'
type ResponseType string

const (
	ResponseTypeCode ResponseType = "code"
)

func (e ResponseType) ToPointer() *ResponseType {
	return &e
}
func (e *ResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "code":
		*e = ResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseType: %v", v)
	}
}

type GetOAuthAuthorizationRequest struct {
	// OAuth response type, must be 'code'
	ResponseType  ResponseType `queryParam:"style=form,explode=true,name=response_type"`
	ClientID      string       `queryParam:"style=form,explode=true,name=client_id"`
	RedirectURI   string       `queryParam:"style=form,explode=true,name=redirect_uri"`
	Scope         string       `queryParam:"style=form,explode=true,name=scope"`
	State         string       `queryParam:"style=form,explode=true,name=state"`
	CodeChallenge *string      `queryParam:"style=form,explode=true,name=code_challenge"`
}

func (g *GetOAuthAuthorizationRequest) GetResponseType() ResponseType {
	if g == nil {
		return ResponseType("")
	}
	return g.ResponseType
}

func (g *GetOAuthAuthorizationRequest) GetClientID() string {
	if g == nil {
		return ""
	}
	return g.ClientID
}

func (g *GetOAuthAuthorizationRequest) GetRedirectURI() string {
	if g == nil {
		return ""
	}
	return g.RedirectURI
}

func (g *GetOAuthAuthorizationRequest) GetScope() string {
	if g == nil {
		return ""
	}
	return g.Scope
}

func (g *GetOAuthAuthorizationRequest) GetState() string {
	if g == nil {
		return ""
	}
	return g.State
}

func (g *GetOAuthAuthorizationRequest) GetCodeChallenge() *string {
	if g == nil {
		return nil
	}
	return g.CodeChallenge
}

// GetOAuthAuthorizationStatus - Application verification status
type GetOAuthAuthorizationStatus string

const (
	GetOAuthAuthorizationStatusDraft    GetOAuthAuthorizationStatus = "draft"
	GetOAuthAuthorizationStatusPending  GetOAuthAuthorizationStatus = "pending"
	GetOAuthAuthorizationStatusApproved GetOAuthAuthorizationStatus = "approved"
	GetOAuthAuthorizationStatusRejected GetOAuthAuthorizationStatus = "rejected"
)

func (e GetOAuthAuthorizationStatus) ToPointer() *GetOAuthAuthorizationStatus {
	return &e
}
func (e *GetOAuthAuthorizationStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "pending":
		fallthrough
	case "approved":
		fallthrough
	case "rejected":
		*e = GetOAuthAuthorizationStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetOAuthAuthorizationStatus: %v", v)
	}
}

// GetOAuthAuthorizationResponseBody - Application information for consent screen
type GetOAuthAuthorizationResponseBody struct {
	// Application ID
	ID string `json:"id"`
	// Application name
	Name string `json:"name"`
	// Application description
	Description *string `json:"description"`
	// Application overview
	Overview *string `json:"overview"`
	// The person or company developing this application
	DeveloperName *string `json:"developerName"`
	// Application logo URL
	LogoURL *string `json:"logoUrl"`
	// Application website
	Website *string `json:"website"`
	// An optional URL for installing the application
	InstallURL *string `json:"installUrl"`
	// Up to 4 screenshots that will be displayed on the apps page
	Screenshots []string `json:"screenshots"`
	// Client ID
	ClientID string `json:"clientId"`
	// Requested scopes
	Scopes []string `json:"scopes"`
	// Redirect URI
	RedirectURI string `json:"redirectUri"`
	// State parameter (min 32 chars, alphanumeric + _.-)
	State *string `json:"state,omitempty"`
	// Application verification status
	Status GetOAuthAuthorizationStatus `json:"status"`
}

func (g *GetOAuthAuthorizationResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOAuthAuthorizationResponseBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetOAuthAuthorizationResponseBody) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetOAuthAuthorizationResponseBody) GetOverview() *string {
	if g == nil {
		return nil
	}
	return g.Overview
}

func (g *GetOAuthAuthorizationResponseBody) GetDeveloperName() *string {
	if g == nil {
		return nil
	}
	return g.DeveloperName
}

func (g *GetOAuthAuthorizationResponseBody) GetLogoURL() *string {
	if g == nil {
		return nil
	}
	return g.LogoURL
}

func (g *GetOAuthAuthorizationResponseBody) GetWebsite() *string {
	if g == nil {
		return nil
	}
	return g.Website
}

func (g *GetOAuthAuthorizationResponseBody) GetInstallURL() *string {
	if g == nil {
		return nil
	}
	return g.InstallURL
}

func (g *GetOAuthAuthorizationResponseBody) GetScreenshots() []string {
	if g == nil {
		return []string{}
	}
	return g.Screenshots
}

func (g *GetOAuthAuthorizationResponseBody) GetClientID() string {
	if g == nil {
		return ""
	}
	return g.ClientID
}

func (g *GetOAuthAuthorizationResponseBody) GetScopes() []string {
	if g == nil {
		return []string{}
	}
	return g.Scopes
}

func (g *GetOAuthAuthorizationResponseBody) GetRedirectURI() string {
	if g == nil {
		return ""
	}
	return g.RedirectURI
}

func (g *GetOAuthAuthorizationResponseBody) GetState() *string {
	if g == nil {
		return nil
	}
	return g.State
}

func (g *GetOAuthAuthorizationResponseBody) GetStatus() GetOAuthAuthorizationStatus {
	if g == nil {
		return GetOAuthAuthorizationStatus("")
	}
	return g.Status
}

type GetOAuthAuthorizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Application information for consent screen
	Object *GetOAuthAuthorizationResponseBody
}

func (g *GetOAuthAuthorizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOAuthAuthorizationResponse) GetObject() *GetOAuthAuthorizationResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
