// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// GetStripeConnectURLResponseBody - Stripe Connect OAuth URL
type GetStripeConnectURLResponseBody struct {
	URL string `json:"url"`
}

func (o *GetStripeConnectURLResponseBody) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetStripeConnectURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Stripe Connect OAuth URL
	Object *GetStripeConnectURLResponseBody
}

func (o *GetStripeConnectURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetStripeConnectURLResponse) GetObject() *GetStripeConnectURLResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
