// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetSpendingReportsRequest struct {
	From     string  `queryParam:"style=form,explode=true,name=from"`
	To       string  `queryParam:"style=form,explode=true,name=to"`
	Currency *string `queryParam:"style=form,explode=true,name=currency"`
}

func (g *GetSpendingReportsRequest) GetFrom() string {
	if g == nil {
		return ""
	}
	return g.From
}

func (g *GetSpendingReportsRequest) GetTo() string {
	if g == nil {
		return ""
	}
	return g.To
}

func (g *GetSpendingReportsRequest) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

type GetSpendingReportsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Spending reports for the authenticated team.
	SpendingResultArray []components.SpendingResultArray
}

func (g *GetSpendingReportsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSpendingReportsResponse) GetSpendingResultArray() []components.SpendingResultArray {
	if g == nil {
		return nil
	}
	return g.SpendingResultArray
}
