// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetSpendingReportsRequest struct {
	// Start date (ISO 8601 format)
	From string `queryParam:"style=form,explode=true,name=from"`
	// End date (ISO 8601 format)
	To string `queryParam:"style=form,explode=true,name=to"`
	// Currency code (ISO 4217)
	Currency *string `queryParam:"style=form,explode=true,name=currency"`
}

func (o *GetSpendingReportsRequest) GetFrom() string {
	if o == nil {
		return ""
	}
	return o.From
}

func (o *GetSpendingReportsRequest) GetTo() string {
	if o == nil {
		return ""
	}
	return o.To
}

func (o *GetSpendingReportsRequest) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

type GetSpendingReportsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Spending reports for the authenticated team.
	SpendingResultArray []components.SpendingResultArray
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *GetSpendingReportsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSpendingReportsResponse) GetSpendingResultArray() []components.SpendingResultArray {
	if o == nil {
		return nil
	}
	return o.SpendingResultArray
}

func (o *GetSpendingReportsResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
