// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// GetSlackInstallURLResponseBody - Slack install URL
type GetSlackInstallURLResponseBody struct {
	URL string `json:"url"`
}

func (o *GetSlackInstallURLResponseBody) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetSlackInstallURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Slack install URL
	Object *GetSlackInstallURLResponseBody
}

func (o *GetSlackInstallURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSlackInstallURLResponse) GetObject() *GetSlackInstallURLResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
