// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetTransactionByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetTransactionByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetTransactionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Transaction details
	TransactionResponse *components.TransactionResponse
}

func (o *GetTransactionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTransactionByIDResponse) GetTransactionResponse() *components.TransactionResponse {
	if o == nil {
		return nil
	}
	return o.TransactionResponse
}
