// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetTrackerProjectByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTrackerProjectByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTrackerProjectByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker project by ID for the authenticated team.
	TrackerProjectResponse *components.TrackerProjectResponse
}

func (g *GetTrackerProjectByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTrackerProjectByIDResponse) GetTrackerProjectResponse() *components.TrackerProjectResponse {
	if g == nil {
		return nil
	}
	return g.TrackerProjectResponse
}
