// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

type GetTransactionAttachmentPreSignedURLRequest struct {
	TransactionID string `pathParam:"style=simple,explode=false,name=transactionId"`
	AttachmentID  string `pathParam:"style=simple,explode=false,name=attachmentId"`
	Download      *bool  `queryParam:"style=form,explode=true,name=download"`
}

func (g *GetTransactionAttachmentPreSignedURLRequest) GetTransactionID() string {
	if g == nil {
		return ""
	}
	return g.TransactionID
}

func (g *GetTransactionAttachmentPreSignedURLRequest) GetAttachmentID() string {
	if g == nil {
		return ""
	}
	return g.AttachmentID
}

func (g *GetTransactionAttachmentPreSignedURLRequest) GetDownload() *bool {
	if g == nil {
		return nil
	}
	return g.Download
}

// GetTransactionAttachmentPreSignedURLResponseBody - Pre-signed URL generated successfully
type GetTransactionAttachmentPreSignedURLResponseBody struct {
	// Pre-signed URL for accessing the attachment, valid for 60 seconds
	URL string `json:"url"`
	// ISO 8601 timestamp when the URL expires
	ExpiresAt time.Time `json:"expiresAt"`
	// Original filename of the attachment
	FileName *string `json:"fileName"`
}

func (g GetTransactionAttachmentPreSignedURLResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionAttachmentPreSignedURLResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"url", "expiresAt", "fileName"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTransactionAttachmentPreSignedURLResponseBody) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

func (g *GetTransactionAttachmentPreSignedURLResponseBody) GetExpiresAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.ExpiresAt
}

func (g *GetTransactionAttachmentPreSignedURLResponseBody) GetFileName() *string {
	if g == nil {
		return nil
	}
	return g.FileName
}

type GetTransactionAttachmentPreSignedURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Pre-signed URL generated successfully
	Object *GetTransactionAttachmentPreSignedURLResponseBody
}

func (g *GetTransactionAttachmentPreSignedURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTransactionAttachmentPreSignedURLResponse) GetObject() *GetTransactionAttachmentPreSignedURLResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
