// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetTimerStatusRequest struct {
	AssignedID *string `queryParam:"style=form,explode=true,name=assignedId"`
}

func (g *GetTimerStatusRequest) GetAssignedID() *string {
	if g == nil {
		return nil
	}
	return g.AssignedID
}

type TrackerProject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (t *TrackerProject) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TrackerProject) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

// CurrentEntry - Current running timer details, null if not running
type CurrentEntry struct {
	ID             string         `json:"id"`
	Start          *string        `json:"start"`
	Description    *string        `json:"description"`
	ProjectID      string         `json:"projectId"`
	TrackerProject TrackerProject `json:"trackerProject"`
}

func (c *CurrentEntry) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CurrentEntry) GetStart() *string {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *CurrentEntry) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CurrentEntry) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CurrentEntry) GetTrackerProject() TrackerProject {
	if c == nil {
		return TrackerProject{}
	}
	return c.TrackerProject
}

type GetTimerStatusData struct {
	// Whether there is currently a running timer
	IsRunning bool `json:"isRunning"`
	// Current running timer details, null if not running
	CurrentEntry *CurrentEntry `json:"currentEntry"`
	// Elapsed time in seconds for the current running timer
	ElapsedTime float64 `json:"elapsedTime"`
}

func (g *GetTimerStatusData) GetIsRunning() bool {
	if g == nil {
		return false
	}
	return g.IsRunning
}

func (g *GetTimerStatusData) GetCurrentEntry() *CurrentEntry {
	if g == nil {
		return nil
	}
	return g.CurrentEntry
}

func (g *GetTimerStatusData) GetElapsedTime() float64 {
	if g == nil {
		return 0.0
	}
	return g.ElapsedTime
}

// GetTimerStatusResponseBody - Timer status retrieved successfully.
type GetTimerStatusResponseBody struct {
	Data GetTimerStatusData `json:"data"`
}

func (g *GetTimerStatusResponseBody) GetData() GetTimerStatusData {
	if g == nil {
		return GetTimerStatusData{}
	}
	return g.Data
}

type GetTimerStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Timer status retrieved successfully.
	Object *GetTimerStatusResponseBody
}

func (g *GetTimerStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTimerStatusResponse) GetObject() *GetTimerStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
