// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type GetTagByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTagByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTagByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a tag by ID for the authenticated team.
	TagResponse *components.TagResponse
}

func (g *GetTagByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTagByIDResponse) GetTagResponse() *components.TagResponse {
	if g == nil {
		return nil
	}
	return g.TagResponse
}
