// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type Error struct {
	Path    string `json:"path"`
	Message string `json:"message"`
}

func (o *Error) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// InboxWebhookResponseBody - Webhook processed successfully
type InboxWebhookResponseBody struct {
	Success bool `json:"success"`
}

func (o *InboxWebhookResponseBody) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

type InboxWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object *InboxWebhookResponseBody
}

func (o *InboxWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *InboxWebhookResponse) GetObject() *InboxWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
