// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type ListBankAccountsRequest struct {
	Enabled *bool `queryParam:"style=form,explode=true,name=enabled"`
	Manual  *bool `queryParam:"style=form,explode=true,name=manual"`
}

func (l *ListBankAccountsRequest) GetEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.Enabled
}

func (l *ListBankAccountsRequest) GetManual() *bool {
	if l == nil {
		return nil
	}
	return l.Manual
}

// ListBankAccountsData - A single bank account object response.
type ListBankAccountsData struct {
	// Unique identifier for the bank account.
	ID string `json:"id"`
	// Name of the bank account.
	Name *string `json:"name"`
	// Currency code of the bank account (e.g., USD, EUR).
	Currency *string `json:"currency"`
	// Type of the bank account (e.g., depository, credit).
	Type *string `json:"type"`
	// Whether the bank account is enabled.
	Enabled bool `json:"enabled"`
	// Current balance of the bank account.
	Balance *float64 `json:"balance"`
	// Whether the bank account is a manual account.
	Manual *bool `json:"manual"`
}

func (l *ListBankAccountsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBankAccountsData) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListBankAccountsData) GetCurrency() *string {
	if l == nil {
		return nil
	}
	return l.Currency
}

func (l *ListBankAccountsData) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListBankAccountsData) GetEnabled() bool {
	if l == nil {
		return false
	}
	return l.Enabled
}

func (l *ListBankAccountsData) GetBalance() *float64 {
	if l == nil {
		return nil
	}
	return l.Balance
}

func (l *ListBankAccountsData) GetManual() *bool {
	if l == nil {
		return nil
	}
	return l.Manual
}

// ListBankAccountsResponseBody - Response containing a list of bank accounts.
type ListBankAccountsResponseBody struct {
	// Array of bank account objects.
	Data []ListBankAccountsData `json:"data"`
}

func (l *ListBankAccountsResponseBody) GetData() []ListBankAccountsData {
	if l == nil {
		return []ListBankAccountsData{}
	}
	return l.Data
}

type ListBankAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a list of bank accounts
	Object *ListBankAccountsResponseBody
}

func (l *ListBankAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListBankAccountsResponse) GetObject() *ListBankAccountsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
