// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

type ListInboxItemsStatus string

const (
	ListInboxItemsStatusDone           ListInboxItemsStatus = "done"
	ListInboxItemsStatusPending        ListInboxItemsStatus = "pending"
	ListInboxItemsStatusSuggestedMatch ListInboxItemsStatus = "suggested_match"
)

func (e ListInboxItemsStatus) ToPointer() *ListInboxItemsStatus {
	return &e
}
func (e *ListInboxItemsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "done":
		fallthrough
	case "pending":
		fallthrough
	case "suggested_match":
		*e = ListInboxItemsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListInboxItemsStatus: %v", v)
	}
}

type ListInboxItemsRequest struct {
	Cursor   *string               `queryParam:"style=form,explode=true,name=cursor"`
	Order    *string               `queryParam:"style=form,explode=true,name=order"`
	PageSize *float64              `queryParam:"style=form,explode=true,name=pageSize"`
	Q        *string               `queryParam:"style=form,explode=true,name=q"`
	Status   *ListInboxItemsStatus `queryParam:"style=form,explode=true,name=status"`
}

func (l *ListInboxItemsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListInboxItemsRequest) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListInboxItemsRequest) GetPageSize() *float64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListInboxItemsRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListInboxItemsRequest) GetStatus() *ListInboxItemsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

// ListInboxItemsMeta - Pagination metadata for the inbox list response.
type ListInboxItemsMeta struct {
	// A cursor for pagination, representing the last item from the previous page.
	Cursor *string `json:"cursor,omitempty"`
	// Whether there is a previous page of results.
	HasPreviousPage bool `json:"hasPreviousPage"`
	// Whether there is a next page of results.
	HasNextPage bool `json:"hasNextPage"`
}

func (l *ListInboxItemsMeta) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListInboxItemsMeta) GetHasPreviousPage() bool {
	if l == nil {
		return false
	}
	return l.HasPreviousPage
}

func (l *ListInboxItemsMeta) GetHasNextPage() bool {
	if l == nil {
		return false
	}
	return l.HasNextPage
}

// ListInboxItemsTransaction - Matched transaction for this inbox item, if any
type ListInboxItemsTransaction struct {
	// Transaction ID (UUID)
	ID string `json:"id"`
	// Transaction amount
	Amount float64 `json:"amount"`
	// Transaction currency (ISO 4217)
	Currency string `json:"currency"`
	// Transaction name or payee
	Name string `json:"name"`
	// Transaction date (ISO 8601)
	Date string `json:"date"`
}

func (l *ListInboxItemsTransaction) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListInboxItemsTransaction) GetAmount() float64 {
	if l == nil {
		return 0.0
	}
	return l.Amount
}

func (l *ListInboxItemsTransaction) GetCurrency() string {
	if l == nil {
		return ""
	}
	return l.Currency
}

func (l *ListInboxItemsTransaction) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListInboxItemsTransaction) GetDate() string {
	if l == nil {
		return ""
	}
	return l.Date
}

// ListInboxItemsData - Inbox item object
type ListInboxItemsData struct {
	// Inbox item ID (UUID)
	ID string `json:"id"`
	// Original file name of the uploaded document
	FileName string `json:"fileName"`
	// Path segments to the file in storage
	FilePath []string `json:"filePath"`
	// Display name for the inbox item
	DisplayName string `json:"displayName"`
	// Amount detected or entered for the inbox item
	Amount *float64 `json:"amount"`
	// Currency code (ISO 4217) for the amount
	Currency *string `json:"currency"`
	// MIME type of the uploaded file
	ContentType *string `json:"contentType"`
	// Date associated with the inbox item (ISO 8601)
	Date *string `json:"date"`
	// Status of the inbox item
	Status string `json:"status"`
	// Date and time when the inbox item was created (ISO 8601)
	CreatedAt string `json:"createdAt"`
	// Website associated with the inbox item, if any
	Website *string `json:"website"`
	// Description or notes for the inbox item
	Description *string `json:"description"`
	// Matched transaction for this inbox item, if any
	Transaction *ListInboxItemsTransaction `json:"transaction"`
}

func (l *ListInboxItemsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListInboxItemsData) GetFileName() string {
	if l == nil {
		return ""
	}
	return l.FileName
}

func (l *ListInboxItemsData) GetFilePath() []string {
	if l == nil {
		return []string{}
	}
	return l.FilePath
}

func (l *ListInboxItemsData) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListInboxItemsData) GetAmount() *float64 {
	if l == nil {
		return nil
	}
	return l.Amount
}

func (l *ListInboxItemsData) GetCurrency() *string {
	if l == nil {
		return nil
	}
	return l.Currency
}

func (l *ListInboxItemsData) GetContentType() *string {
	if l == nil {
		return nil
	}
	return l.ContentType
}

func (l *ListInboxItemsData) GetDate() *string {
	if l == nil {
		return nil
	}
	return l.Date
}

func (l *ListInboxItemsData) GetStatus() string {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListInboxItemsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListInboxItemsData) GetWebsite() *string {
	if l == nil {
		return nil
	}
	return l.Website
}

func (l *ListInboxItemsData) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *ListInboxItemsData) GetTransaction() *ListInboxItemsTransaction {
	if l == nil {
		return nil
	}
	return l.Transaction
}

// ListInboxItemsResponseBody - Retrieve a list of inbox items for the authenticated team.
type ListInboxItemsResponseBody struct {
	// Pagination metadata for the inbox list response.
	Meta ListInboxItemsMeta `json:"meta"`
	// List of inbox items
	Data []ListInboxItemsData `json:"data"`
}

func (l *ListInboxItemsResponseBody) GetMeta() ListInboxItemsMeta {
	if l == nil {
		return ListInboxItemsMeta{}
	}
	return l.Meta
}

func (l *ListInboxItemsResponseBody) GetData() []ListInboxItemsData {
	if l == nil {
		return []ListInboxItemsData{}
	}
	return l.Data
}

type ListInboxItemsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a list of inbox items for the authenticated team.
	Object *ListInboxItemsResponseBody
}

func (l *ListInboxItemsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInboxItemsResponse) GetObject() *ListInboxItemsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
