// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

type ListTeamMembersRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListTeamMembersRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

// Role of the team member. 'owner' has full permissions, 'member' has limited permissions
type Role string

const (
	RoleOwner  Role = "owner"
	RoleMember Role = "member"
)

func (e Role) ToPointer() *Role {
	return &e
}
func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "owner":
		fallthrough
	case "member":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}

type ListTeamMembersData struct {
	// Unique identifier of the user
	ID string `json:"id"`
	// Role of the team member. 'owner' has full permissions, 'member' has limited permissions
	Role Role `json:"role"`
	// Full name of the team member
	FullName string `json:"fullName"`
	// URL to the team member's avatar image
	AvatarURL *string `json:"avatarUrl"`
}

func (l *ListTeamMembersData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListTeamMembersData) GetRole() Role {
	if l == nil {
		return Role("")
	}
	return l.Role
}

func (l *ListTeamMembersData) GetFullName() string {
	if l == nil {
		return ""
	}
	return l.FullName
}

func (l *ListTeamMembersData) GetAvatarURL() *string {
	if l == nil {
		return nil
	}
	return l.AvatarURL
}

// ListTeamMembersResponseBody - Team members
type ListTeamMembersResponseBody struct {
	// Array of team members with their roles and information
	Data []ListTeamMembersData `json:"data"`
}

func (l *ListTeamMembersResponseBody) GetData() []ListTeamMembersData {
	if l == nil {
		return []ListTeamMembersData{}
	}
	return l.Data
}

type ListTeamMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Team members
	Object *ListTeamMembersResponseBody
}

func (l *ListTeamMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTeamMembersResponse) GetObject() *ListTeamMembersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
