// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type ListDocumentsRequest struct {
	Cursor   *string  `queryParam:"style=form,explode=true,name=cursor"`
	Sort     []string `queryParam:"style=form,explode=true,name=sort"`
	PageSize *float64 `queryParam:"style=form,explode=true,name=pageSize"`
	Q        *string  `queryParam:"style=form,explode=true,name=q"`
	Tags     []string `queryParam:"style=form,explode=true,name=tags"`
}

func (l *ListDocumentsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListDocumentsRequest) GetSort() []string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListDocumentsRequest) GetPageSize() *float64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListDocumentsRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListDocumentsRequest) GetTags() []string {
	if l == nil {
		return nil
	}
	return l.Tags
}

// ListDocumentsMeta - Pagination metadata for the documents list.
type ListDocumentsMeta struct {
	// Cursor for pagination.
	Cursor *string `json:"cursor,omitempty"`
	// Whether there is a previous page.
	HasPreviousPage bool `json:"hasPreviousPage"`
	// Whether there is a next page.
	HasNextPage bool `json:"hasNextPage"`
}

func (l *ListDocumentsMeta) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListDocumentsMeta) GetHasPreviousPage() bool {
	if l == nil {
		return false
	}
	return l.HasPreviousPage
}

func (l *ListDocumentsMeta) GetHasNextPage() bool {
	if l == nil {
		return false
	}
	return l.HasNextPage
}

// ListDocumentsMetadata - Metadata about the document.
type ListDocumentsMetadata struct {
	// Size of the document in bytes.
	Size *float64 `json:"size"`
	// MIME type of the document.
	Mimetype *string `json:"mimetype"`
}

func (l *ListDocumentsMetadata) GetSize() *float64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListDocumentsMetadata) GetMimetype() *string {
	if l == nil {
		return nil
	}
	return l.Mimetype
}

// ListDocumentsData - A single document object response.
type ListDocumentsData struct {
	// Unique identifier for the document.
	ID string `json:"id"`
	// Title of the document.
	Title *string `json:"title"`
	// Array of path tokens representing the document's location.
	PathTokens []string `json:"pathTokens"`
	// Metadata about the document.
	Metadata *ListDocumentsMetadata `json:"metadata"`
	// Processing status of the document.
	ProcessingStatus string `json:"processingStatus"`
	// Summary or extracted content from the document.
	Summary *string `json:"summary"`
	// Date associated with the document (ISO 8601).
	Date *string `json:"date"`
}

func (l *ListDocumentsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListDocumentsData) GetTitle() *string {
	if l == nil {
		return nil
	}
	return l.Title
}

func (l *ListDocumentsData) GetPathTokens() []string {
	if l == nil {
		return []string{}
	}
	return l.PathTokens
}

func (l *ListDocumentsData) GetMetadata() *ListDocumentsMetadata {
	if l == nil {
		return nil
	}
	return l.Metadata
}

func (l *ListDocumentsData) GetProcessingStatus() string {
	if l == nil {
		return ""
	}
	return l.ProcessingStatus
}

func (l *ListDocumentsData) GetSummary() *string {
	if l == nil {
		return nil
	}
	return l.Summary
}

func (l *ListDocumentsData) GetDate() *string {
	if l == nil {
		return nil
	}
	return l.Date
}

// ListDocumentsResponseBody - Response containing a list of documents and pagination metadata.
type ListDocumentsResponseBody struct {
	// Pagination metadata for the documents list.
	Meta ListDocumentsMeta `json:"meta"`
	// Array of document objects.
	Data []ListDocumentsData `json:"data"`
}

func (l *ListDocumentsResponseBody) GetMeta() ListDocumentsMeta {
	if l == nil {
		return ListDocumentsMeta{}
	}
	return l.Meta
}

func (l *ListDocumentsResponseBody) GetData() []ListDocumentsData {
	if l == nil {
		return []ListDocumentsData{}
	}
	return l.Data
}

type ListDocumentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a list of documents for the authenticated team.
	Object *ListDocumentsResponseBody
}

func (l *ListDocumentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListDocumentsResponse) GetObject() *ListDocumentsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
