// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

// ListTeamsPlan - Current subscription plan of the team
type ListTeamsPlan string

const (
	ListTeamsPlanTrial   ListTeamsPlan = "trial"
	ListTeamsPlanStarter ListTeamsPlan = "starter"
	ListTeamsPlanPro     ListTeamsPlan = "pro"
)

func (e ListTeamsPlan) ToPointer() *ListTeamsPlan {
	return &e
}
func (e *ListTeamsPlan) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trial":
		fallthrough
	case "starter":
		fallthrough
	case "pro":
		*e = ListTeamsPlan(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTeamsPlan: %v", v)
	}
}

type ListTeamsData struct {
	// Unique identifier of the team
	ID string `json:"id"`
	// Name of the team or organization
	Name string `json:"name"`
	// URL to the team's logo image
	LogoURL *string `json:"logoUrl"`
	// Current subscription plan of the team
	Plan ListTeamsPlan `json:"plan"`
}

func (l *ListTeamsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListTeamsData) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListTeamsData) GetLogoURL() *string {
	if l == nil {
		return nil
	}
	return l.LogoURL
}

func (l *ListTeamsData) GetPlan() ListTeamsPlan {
	if l == nil {
		return ListTeamsPlan("")
	}
	return l.Plan
}

// ListTeamsResponseBody - Retrieve a list of teams for the authenticated user.
type ListTeamsResponseBody struct {
	// Array of teams that the user has access to
	Data []ListTeamsData `json:"data"`
}

func (l *ListTeamsResponseBody) GetData() []ListTeamsData {
	if l == nil {
		return []ListTeamsData{}
	}
	return l.Data
}

type ListTeamsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a list of teams for the authenticated user.
	Object *ListTeamsResponseBody
}

func (l *ListTeamsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTeamsResponse) GetObject() *ListTeamsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
