// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type OutlookOAuthCallbackRequest struct {
	// OAuth authorization code from Microsoft
	Code *string `queryParam:"style=form,explode=true,name=code"`
	// Encrypted OAuth state parameter
	State string `queryParam:"style=form,explode=true,name=state"`
	// OAuth error code if authorization failed
	Error *string `queryParam:"style=form,explode=true,name=error"`
}

func (o *OutlookOAuthCallbackRequest) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *OutlookOAuthCallbackRequest) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}

func (o *OutlookOAuthCallbackRequest) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type OutlookOAuthCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *OutlookOAuthCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OutlookOAuthCallbackResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
