// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// PolarWebhookResponseBody - Webhook processed successfully
type PolarWebhookResponseBody struct {
	Received bool `json:"received"`
}

func (o *PolarWebhookResponseBody) GetReceived() bool {
	if o == nil {
		return false
	}
	return o.Received
}

type PolarWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object *PolarWebhookResponseBody
}

func (o *PolarWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PolarWebhookResponse) GetObject() *PolarWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
