// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
)

type PostOAuthRegisterRequest struct {
	// Human-readable name of the client
	ClientName string `json:"client_name"`
	// Array of redirect URIs
	RedirectUris []string `json:"redirect_uris"`
	// Requested grant types
	GrantTypes []string `json:"grant_types,omitempty"`
	// Token endpoint authentication method
	TokenEndpointAuthMethod *string `default:"none" json:"token_endpoint_auth_method"`
	// Space-separated requested scopes
	Scope *string `json:"scope,omitempty"`
	// URL of the client logo
	LogoURI *string `json:"logo_uri,omitempty"`
	// URL of the client homepage
	ClientURI *string `json:"client_uri,omitempty"`
	// Requested response types
	ResponseTypes []string `json:"response_types,omitempty"`
}

func (p PostOAuthRegisterRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostOAuthRegisterRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PostOAuthRegisterRequest) GetClientName() string {
	if o == nil {
		return ""
	}
	return o.ClientName
}

func (o *PostOAuthRegisterRequest) GetRedirectUris() []string {
	if o == nil {
		return []string{}
	}
	return o.RedirectUris
}

func (o *PostOAuthRegisterRequest) GetGrantTypes() []string {
	if o == nil {
		return nil
	}
	return o.GrantTypes
}

func (o *PostOAuthRegisterRequest) GetTokenEndpointAuthMethod() *string {
	if o == nil {
		return nil
	}
	return o.TokenEndpointAuthMethod
}

func (o *PostOAuthRegisterRequest) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *PostOAuthRegisterRequest) GetLogoURI() *string {
	if o == nil {
		return nil
	}
	return o.LogoURI
}

func (o *PostOAuthRegisterRequest) GetClientURI() *string {
	if o == nil {
		return nil
	}
	return o.ClientURI
}

func (o *PostOAuthRegisterRequest) GetResponseTypes() []string {
	if o == nil {
		return nil
	}
	return o.ResponseTypes
}

// PostOAuthRegisterResponseBody2 - Client registered successfully
type PostOAuthRegisterResponseBody2 struct {
	// Assigned client ID
	ClientID string `json:"client_id"`
	// Human-readable name of the client
	ClientName string `json:"client_name"`
	// Registered redirect URIs
	RedirectUris []string `json:"redirect_uris"`
	// Granted grant types
	GrantTypes []string `json:"grant_types"`
	// Token endpoint authentication method
	TokenEndpointAuthMethod string `json:"token_endpoint_auth_method"`
	// Supported response types
	ResponseTypes []string `json:"response_types"`
}

func (o *PostOAuthRegisterResponseBody2) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *PostOAuthRegisterResponseBody2) GetClientName() string {
	if o == nil {
		return ""
	}
	return o.ClientName
}

func (o *PostOAuthRegisterResponseBody2) GetRedirectUris() []string {
	if o == nil {
		return []string{}
	}
	return o.RedirectUris
}

func (o *PostOAuthRegisterResponseBody2) GetGrantTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.GrantTypes
}

func (o *PostOAuthRegisterResponseBody2) GetTokenEndpointAuthMethod() string {
	if o == nil {
		return ""
	}
	return o.TokenEndpointAuthMethod
}

func (o *PostOAuthRegisterResponseBody2) GetResponseTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.ResponseTypes
}

// PostOAuthRegisterResponseBody1 - Existing client returned (deduplicated)
type PostOAuthRegisterResponseBody1 struct {
	// Assigned client ID
	ClientID string `json:"client_id"`
	// Human-readable name of the client
	ClientName string `json:"client_name"`
	// Registered redirect URIs
	RedirectUris []string `json:"redirect_uris"`
	// Granted grant types
	GrantTypes []string `json:"grant_types"`
	// Token endpoint authentication method
	TokenEndpointAuthMethod string `json:"token_endpoint_auth_method"`
	// Supported response types
	ResponseTypes []string `json:"response_types"`
}

func (o *PostOAuthRegisterResponseBody1) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *PostOAuthRegisterResponseBody1) GetClientName() string {
	if o == nil {
		return ""
	}
	return o.ClientName
}

func (o *PostOAuthRegisterResponseBody1) GetRedirectUris() []string {
	if o == nil {
		return []string{}
	}
	return o.RedirectUris
}

func (o *PostOAuthRegisterResponseBody1) GetGrantTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.GrantTypes
}

func (o *PostOAuthRegisterResponseBody1) GetTokenEndpointAuthMethod() string {
	if o == nil {
		return ""
	}
	return o.TokenEndpointAuthMethod
}

func (o *PostOAuthRegisterResponseBody1) GetResponseTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.ResponseTypes
}

type PostOAuthRegisterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Existing client returned (deduplicated)
	TwoHundredApplicationJSONObject *PostOAuthRegisterResponseBody1
	// Client registered successfully
	TwoHundredAndOneApplicationJSONObject *PostOAuthRegisterResponseBody2
}

func (o *PostOAuthRegisterResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostOAuthRegisterResponse) GetTwoHundredApplicationJSONObject() *PostOAuthRegisterResponseBody1 {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostOAuthRegisterResponse) GetTwoHundredAndOneApplicationJSONObject() *PostOAuthRegisterResponseBody2 {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}
