// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// SlackInteractionsResponseBody - Interaction handled successfully
type SlackInteractionsResponseBody struct {
	Ok bool `json:"ok"`
}

func (o *SlackInteractionsResponseBody) GetOk() bool {
	if o == nil {
		return false
	}
	return o.Ok
}

type SlackInteractionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Interaction handled successfully
	Object *SlackInteractionsResponseBody
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *SlackInteractionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SlackInteractionsResponse) GetObject() *SlackInteractionsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *SlackInteractionsResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
