// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

type StopTimerRequest struct {
	// Unique identifier of the specific timer entry to stop. If not provided, will stop the current running timer for the user
	EntryID *string `json:"entryId,omitempty"`
	// Unique identifier of the user whose timer should be stopped. If not provided, will use the authenticated user
	AssignedID *string `json:"assignedId,omitempty"`
	// Stop time in ISO 8601 format. If not provided, will use current time
	Stop *time.Time `json:"stop,omitempty"`
}

func (s StopTimerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StopTimerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StopTimerRequest) GetEntryID() *string {
	if s == nil {
		return nil
	}
	return s.EntryID
}

func (s *StopTimerRequest) GetAssignedID() *string {
	if s == nil {
		return nil
	}
	return s.AssignedID
}

func (s *StopTimerRequest) GetStop() *time.Time {
	if s == nil {
		return nil
	}
	return s.Stop
}

// StopTimerUser - User information for the person who created this tracker entry
type StopTimerUser struct {
	// Unique identifier of the user
	ID string `json:"id"`
	// Full name of the user
	FullName string `json:"fullName"`
	// URL to the user's avatar image
	AvatarURL string `json:"avatarUrl"`
}

func (s *StopTimerUser) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StopTimerUser) GetFullName() string {
	if s == nil {
		return ""
	}
	return s.FullName
}

func (s *StopTimerUser) GetAvatarURL() string {
	if s == nil {
		return ""
	}
	return s.AvatarURL
}

// StopTimerCustomer - Customer information associated with the project
type StopTimerCustomer struct {
	// Unique identifier of the customer
	ID string `json:"id"`
	// Name of the customer or organization
	Name string `json:"name"`
}

func (s *StopTimerCustomer) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StopTimerCustomer) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

// StopTimerProject - Project information associated with this tracker entry
type StopTimerProject struct {
	// Unique identifier of the project
	ID string `json:"id"`
	// Date and time when the project was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Default hourly rate for the project
	Rate *float64 `json:"rate"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Current status of the project
	Status string `json:"status"`
	// Description of the project
	Description *string `json:"description"`
	// Name of the project
	Name string `json:"name"`
	// Whether the project is billable to the customer
	Billable *bool `json:"billable"`
	// Estimated total hours for the project
	Estimate *float64 `json:"estimate"`
	// Customer information associated with the project
	Customer *StopTimerCustomer `json:"customer"`
}

func (s *StopTimerProject) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StopTimerProject) GetCreatedAt() string {
	if s == nil {
		return ""
	}
	return s.CreatedAt
}

func (s *StopTimerProject) GetRate() *float64 {
	if s == nil {
		return nil
	}
	return s.Rate
}

func (s *StopTimerProject) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *StopTimerProject) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *StopTimerProject) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *StopTimerProject) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StopTimerProject) GetBillable() *bool {
	if s == nil {
		return nil
	}
	return s.Billable
}

func (s *StopTimerProject) GetEstimate() *float64 {
	if s == nil {
		return nil
	}
	return s.Estimate
}

func (s *StopTimerProject) GetCustomer() *StopTimerCustomer {
	if s == nil {
		return nil
	}
	return s.Customer
}

type StopTimerData struct {
	// Unique identifier of the tracker entry
	ID string `json:"id"`
	// Date and time when the tracker entry was created in ISO 8601 format
	CreatedAt string `json:"createdAt"`
	// Duration of the timer entry in seconds. -1 indicates running, null for paused, positive number for completed
	Duration *float64 `json:"duration"`
	// Start time of the tracker entry in ISO 8601 format
	Start string `json:"start"`
	// Stop time of the tracker entry in ISO 8601 format
	Stop string `json:"stop"`
	// Unique identifier of the team that owns this tracker entry
	TeamID string `json:"teamId"`
	// Description or notes for the tracker entry
	Description *string `json:"description"`
	// Hourly rate applied to this tracker entry
	Rate *float64 `json:"rate"`
	// Currency code for the rate in ISO 4217 format
	Currency *string `json:"currency"`
	// Whether this tracker entry has been billed to the customer
	Billed bool `json:"billed"`
	// Date of the tracker entry in YYYY-MM-DD format
	Date string `json:"date"`
	// User information for the person who created this tracker entry
	User StopTimerUser `json:"user"`
	// Project information associated with this tracker entry
	Project StopTimerProject `json:"project"`
}

func (s *StopTimerData) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StopTimerData) GetCreatedAt() string {
	if s == nil {
		return ""
	}
	return s.CreatedAt
}

func (s *StopTimerData) GetDuration() *float64 {
	if s == nil {
		return nil
	}
	return s.Duration
}

func (s *StopTimerData) GetStart() string {
	if s == nil {
		return ""
	}
	return s.Start
}

func (s *StopTimerData) GetStop() string {
	if s == nil {
		return ""
	}
	return s.Stop
}

func (s *StopTimerData) GetTeamID() string {
	if s == nil {
		return ""
	}
	return s.TeamID
}

func (s *StopTimerData) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *StopTimerData) GetRate() *float64 {
	if s == nil {
		return nil
	}
	return s.Rate
}

func (s *StopTimerData) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *StopTimerData) GetBilled() bool {
	if s == nil {
		return false
	}
	return s.Billed
}

func (s *StopTimerData) GetDate() string {
	if s == nil {
		return ""
	}
	return s.Date
}

func (s *StopTimerData) GetUser() StopTimerUser {
	if s == nil {
		return StopTimerUser{}
	}
	return s.User
}

func (s *StopTimerData) GetProject() StopTimerProject {
	if s == nil {
		return StopTimerProject{}
	}
	return s.Project
}

// StopTimerResponseBody - Timer stopped successfully.
type StopTimerResponseBody struct {
	Data StopTimerData `json:"data"`
}

func (s *StopTimerResponseBody) GetData() StopTimerData {
	if s == nil {
		return StopTimerData{}
	}
	return s.Data
}

type StopTimerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Timer stopped successfully.
	Object *StopTimerResponseBody
}

func (s *StopTimerResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StopTimerResponse) GetObject() *StopTimerResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
