// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// StripeWebhookResponseBody - Webhook processed successfully
type StripeWebhookResponseBody struct {
	Received bool `json:"received"`
}

func (o *StripeWebhookResponseBody) GetReceived() bool {
	if o == nil {
		return false
	}
	return o.Received
}

type StripeWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object *StripeWebhookResponseBody
}

func (o *StripeWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StripeWebhookResponse) GetObject() *StripeWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
