// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type StripeConnectCallbackRequest struct {
	// OAuth authorization code from Stripe
	Code *string `queryParam:"style=form,explode=true,name=code"`
	// OAuth state parameter for CSRF protection
	State string `queryParam:"style=form,explode=true,name=state"`
	// OAuth error code if authorization failed
	Error *string `queryParam:"style=form,explode=true,name=error"`
	// OAuth error description
	ErrorDescription *string `queryParam:"style=form,explode=true,name=error_description"`
}

func (o *StripeConnectCallbackRequest) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StripeConnectCallbackRequest) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}

func (o *StripeConnectCallbackRequest) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *StripeConnectCallbackRequest) GetErrorDescription() *string {
	if o == nil {
		return nil
	}
	return o.ErrorDescription
}

type StripeConnectCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *StripeConnectCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StripeConnectCallbackResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
