// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// TellerWebhookResponseBody - Webhook processed successfully
type TellerWebhookResponseBody struct {
	Success bool `json:"success"`
}

func (o *TellerWebhookResponseBody) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

type TellerWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object *TellerWebhookResponseBody
}

func (o *TellerWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TellerWebhookResponse) GetObject() *TellerWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
