// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
)

// UpdateTrackerProjectStatus - Current status of the project
type UpdateTrackerProjectStatus string

const (
	UpdateTrackerProjectStatusInProgress UpdateTrackerProjectStatus = "in_progress"
	UpdateTrackerProjectStatusCompleted  UpdateTrackerProjectStatus = "completed"
)

func (e UpdateTrackerProjectStatus) ToPointer() *UpdateTrackerProjectStatus {
	return &e
}
func (e *UpdateTrackerProjectStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_progress":
		fallthrough
	case "completed":
		*e = UpdateTrackerProjectStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateTrackerProjectStatus: %v", v)
	}
}

type UpdateTrackerProjectTag struct {
	// Unique identifier of the tag
	ID string `json:"id"`
	// Display value of the tag
	Value string `json:"value"`
}

func (u *UpdateTrackerProjectTag) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTrackerProjectTag) GetValue() string {
	if u == nil {
		return ""
	}
	return u.Value
}

type UpdateTrackerProjectRequestBody struct {
	// Name of the project
	Name string `json:"name"`
	// Detailed description of the project
	Description *string `json:"description,omitempty"`
	// Estimated total hours required to complete the project
	Estimate *float64 `json:"estimate,omitempty"`
	// Whether the project is billable to the customer
	Billable *bool `default:"false" json:"billable"`
	// Hourly rate for the project in the specified currency
	Rate *float64 `json:"rate,omitempty"`
	// Currency code for the project rate in ISO 4217 format
	Currency *string `json:"currency,omitempty"`
	// Current status of the project
	Status *UpdateTrackerProjectStatus `json:"status,omitempty"`
	// Unique identifier of the customer associated with this project
	CustomerID *string `json:"customerId,omitempty"`
	// Array of tags to associate with the project
	Tags []UpdateTrackerProjectTag `json:"tags,omitempty"`
}

func (u UpdateTrackerProjectRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTrackerProjectRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTrackerProjectRequestBody) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateTrackerProjectRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateTrackerProjectRequestBody) GetEstimate() *float64 {
	if u == nil {
		return nil
	}
	return u.Estimate
}

func (u *UpdateTrackerProjectRequestBody) GetBillable() *bool {
	if u == nil {
		return nil
	}
	return u.Billable
}

func (u *UpdateTrackerProjectRequestBody) GetRate() *float64 {
	if u == nil {
		return nil
	}
	return u.Rate
}

func (u *UpdateTrackerProjectRequestBody) GetCurrency() *string {
	if u == nil {
		return nil
	}
	return u.Currency
}

func (u *UpdateTrackerProjectRequestBody) GetStatus() *UpdateTrackerProjectStatus {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateTrackerProjectRequestBody) GetCustomerID() *string {
	if u == nil {
		return nil
	}
	return u.CustomerID
}

func (u *UpdateTrackerProjectRequestBody) GetTags() []UpdateTrackerProjectTag {
	if u == nil {
		return nil
	}
	return u.Tags
}

type UpdateTrackerProjectRequest struct {
	ID          string                           `pathParam:"style=simple,explode=false,name=id"`
	RequestBody *UpdateTrackerProjectRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateTrackerProjectRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTrackerProjectRequest) GetRequestBody() *UpdateTrackerProjectRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}

type UpdateTrackerProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tracker project updated successfully.
	TrackerProjectResponse *components.TrackerProjectResponse
}

func (u *UpdateTrackerProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateTrackerProjectResponse) GetTrackerProjectResponse() *components.TrackerProjectResponse {
	if u == nil {
		return nil
	}
	return u.TrackerProjectResponse
}
