// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/internal/utils"
	"github.com/midday-ai/midday-go/models/components"
	"time"
)

// UpdateInvoiceStatusRequest - New status for the invoice
type UpdateInvoiceStatusRequest string

const (
	UpdateInvoiceStatusRequestPaid      UpdateInvoiceStatusRequest = "paid"
	UpdateInvoiceStatusRequestCanceled  UpdateInvoiceStatusRequest = "canceled"
	UpdateInvoiceStatusRequestUnpaid    UpdateInvoiceStatusRequest = "unpaid"
	UpdateInvoiceStatusRequestScheduled UpdateInvoiceStatusRequest = "scheduled"
	UpdateInvoiceStatusRequestDraft     UpdateInvoiceStatusRequest = "draft"
)

func (e UpdateInvoiceStatusRequest) ToPointer() *UpdateInvoiceStatusRequest {
	return &e
}
func (e *UpdateInvoiceStatusRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "paid":
		fallthrough
	case "canceled":
		fallthrough
	case "unpaid":
		fallthrough
	case "scheduled":
		fallthrough
	case "draft":
		*e = UpdateInvoiceStatusRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateInvoiceStatusRequest: %v", v)
	}
}

// UpdateInvoiceRequestBody - Schema for updating an invoice
type UpdateInvoiceRequestBody struct {
	// New status for the invoice
	Status *UpdateInvoiceStatusRequest `json:"status,omitempty"`
	// Timestamp when the invoice was paid (ISO 8601)
	PaidAt *time.Time `json:"paidAt,omitempty"`
	// Internal note for the invoice
	InternalNote *string `json:"internalNote,omitempty"`
}

func (u UpdateInvoiceRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateInvoiceRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateInvoiceRequestBody) GetStatus() *UpdateInvoiceStatusRequest {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UpdateInvoiceRequestBody) GetPaidAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.PaidAt
}

func (o *UpdateInvoiceRequestBody) GetInternalNote() *string {
	if o == nil {
		return nil
	}
	return o.InternalNote
}

type UpdateInvoiceRequest struct {
	ID          string                    `pathParam:"style=simple,explode=false,name=id"`
	RequestBody *UpdateInvoiceRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateInvoiceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateInvoiceRequest) GetRequestBody() *UpdateInvoiceRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// UpdateInvoiceStatusResponse - Current status of the invoice
type UpdateInvoiceStatusResponse string

const (
	UpdateInvoiceStatusResponseDraft     UpdateInvoiceStatusResponse = "draft"
	UpdateInvoiceStatusResponseOverdue   UpdateInvoiceStatusResponse = "overdue"
	UpdateInvoiceStatusResponsePaid      UpdateInvoiceStatusResponse = "paid"
	UpdateInvoiceStatusResponseUnpaid    UpdateInvoiceStatusResponse = "unpaid"
	UpdateInvoiceStatusResponseCanceled  UpdateInvoiceStatusResponse = "canceled"
	UpdateInvoiceStatusResponseScheduled UpdateInvoiceStatusResponse = "scheduled"
)

func (e UpdateInvoiceStatusResponse) ToPointer() *UpdateInvoiceStatusResponse {
	return &e
}
func (e *UpdateInvoiceStatusResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "overdue":
		fallthrough
	case "paid":
		fallthrough
	case "unpaid":
		fallthrough
	case "canceled":
		fallthrough
	case "scheduled":
		*e = UpdateInvoiceStatusResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateInvoiceStatusResponse: %v", v)
	}
}

// UpdateInvoiceCustomer - Customer details
type UpdateInvoiceCustomer struct {
	// Unique identifier for the customer
	ID string `json:"id"`
	// Name of the customer
	Name string `json:"name"`
	// Website URL of the customer
	Website *string `json:"website"`
	// Email address of the customer
	Email *string `json:"email"`
}

func (o *UpdateInvoiceCustomer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateInvoiceCustomer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateInvoiceCustomer) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}

func (o *UpdateInvoiceCustomer) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

// UpdateInvoiceResponseBody - Response after updating an invoice
type UpdateInvoiceResponseBody struct {
	// Unique identifier for the invoice
	ID string `json:"id"`
	// Current status of the invoice
	Status UpdateInvoiceStatusResponse `json:"status"`
	// Due date of the invoice in ISO 8601 format
	DueDate string `json:"dueDate"`
	// Issue date of the invoice in ISO 8601 format
	IssueDate string `json:"issueDate"`
	// Invoice number as shown to the customer (auto-generated if not provided)
	InvoiceNumber *string `json:"invoiceNumber,omitempty"`
	// Total amount of the invoice
	Amount float64 `json:"amount"`
	// Currency code (ISO 4217) for the invoice amount
	Currency string `json:"currency"`
	// Customer details
	Customer *UpdateInvoiceCustomer `json:"customer"`
	// Timestamp when the invoice was paid (ISO 8601), or null if unpaid
	PaidAt *string `json:"paidAt"`
	// Timestamp when a payment reminder was sent (ISO 8601), or null if never sent
	ReminderSentAt *string `json:"reminderSentAt"`
	// Optional note attached to the invoice
	Note *string `json:"note"`
	// Value-added tax amount, or null if not applicable
	Vat *float64 `json:"vat"`
	// Tax amount, or null if not applicable
	Tax *float64 `json:"tax"`
	// Discount amount applied to the invoice, or null if none
	Discount *float64 `json:"discount"`
	// Subtotal before taxes and discounts, or null if not calculated
	Subtotal *float64 `json:"subtotal"`
	// Timestamp when the invoice was viewed by the customer (ISO 8601), or null if never viewed
	ViewedAt *string `json:"viewedAt"`
	// Name of the customer as shown on the invoice, or null if not set
	CustomerName *string `json:"customerName"`
	// Email address to which the invoice was sent, or null if not sent
	SentTo *string `json:"sentTo"`
	// Timestamp when the invoice was sent (ISO 8601), or null if not sent
	SentAt *string `json:"sentAt"`
	// Timestamp when the invoice was created (ISO 8601)
	CreatedAt string `json:"createdAt"`
	// Timestamp when the invoice was last updated (ISO 8601)
	UpdatedAt string `json:"updatedAt"`
	// URL to download the invoice PDF, or null if not generated
	PdfURL *string `json:"pdfUrl"`
	// URL to preview the invoice in the browser, or null if not generated
	PreviewURL *string `json:"previewUrl"`
}

func (o *UpdateInvoiceResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateInvoiceResponseBody) GetStatus() UpdateInvoiceStatusResponse {
	if o == nil {
		return UpdateInvoiceStatusResponse("")
	}
	return o.Status
}

func (o *UpdateInvoiceResponseBody) GetDueDate() string {
	if o == nil {
		return ""
	}
	return o.DueDate
}

func (o *UpdateInvoiceResponseBody) GetIssueDate() string {
	if o == nil {
		return ""
	}
	return o.IssueDate
}

func (o *UpdateInvoiceResponseBody) GetInvoiceNumber() *string {
	if o == nil {
		return nil
	}
	return o.InvoiceNumber
}

func (o *UpdateInvoiceResponseBody) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *UpdateInvoiceResponseBody) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *UpdateInvoiceResponseBody) GetCustomer() *UpdateInvoiceCustomer {
	if o == nil {
		return nil
	}
	return o.Customer
}

func (o *UpdateInvoiceResponseBody) GetPaidAt() *string {
	if o == nil {
		return nil
	}
	return o.PaidAt
}

func (o *UpdateInvoiceResponseBody) GetReminderSentAt() *string {
	if o == nil {
		return nil
	}
	return o.ReminderSentAt
}

func (o *UpdateInvoiceResponseBody) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}

func (o *UpdateInvoiceResponseBody) GetVat() *float64 {
	if o == nil {
		return nil
	}
	return o.Vat
}

func (o *UpdateInvoiceResponseBody) GetTax() *float64 {
	if o == nil {
		return nil
	}
	return o.Tax
}

func (o *UpdateInvoiceResponseBody) GetDiscount() *float64 {
	if o == nil {
		return nil
	}
	return o.Discount
}

func (o *UpdateInvoiceResponseBody) GetSubtotal() *float64 {
	if o == nil {
		return nil
	}
	return o.Subtotal
}

func (o *UpdateInvoiceResponseBody) GetViewedAt() *string {
	if o == nil {
		return nil
	}
	return o.ViewedAt
}

func (o *UpdateInvoiceResponseBody) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *UpdateInvoiceResponseBody) GetSentTo() *string {
	if o == nil {
		return nil
	}
	return o.SentTo
}

func (o *UpdateInvoiceResponseBody) GetSentAt() *string {
	if o == nil {
		return nil
	}
	return o.SentAt
}

func (o *UpdateInvoiceResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *UpdateInvoiceResponseBody) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *UpdateInvoiceResponseBody) GetPdfURL() *string {
	if o == nil {
		return nil
	}
	return o.PdfURL
}

func (o *UpdateInvoiceResponseBody) GetPreviewURL() *string {
	if o == nil {
		return nil
	}
	return o.PreviewURL
}

type UpdateInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invoice updated successfully.
	Object *UpdateInvoiceResponseBody
}

func (o *UpdateInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateInvoiceResponse) GetObject() *UpdateInvoiceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
