// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type UpdateAllNotificationsStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// All notifications status updated successfully.
	UpdateAllNotificationsStatusResponseSchema *components.UpdateAllNotificationsStatusResponseSchema
	// An error occurred
	ErrorResponse *components.ErrorResponse
}

func (o *UpdateAllNotificationsStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAllNotificationsStatusResponse) GetUpdateAllNotificationsStatusResponseSchema() *components.UpdateAllNotificationsStatusResponseSchema {
	if o == nil {
		return nil
	}
	return o.UpdateAllNotificationsStatusResponseSchema
}

func (o *UpdateAllNotificationsStatusResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
