// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/midday-ai/midday-go/models/components"
)

// UpdateBankAccountType - Type of the bank account.
type UpdateBankAccountType string

const (
	UpdateBankAccountTypeDepository     UpdateBankAccountType = "depository"
	UpdateBankAccountTypeCredit         UpdateBankAccountType = "credit"
	UpdateBankAccountTypeOtherAsset     UpdateBankAccountType = "other_asset"
	UpdateBankAccountTypeLoan           UpdateBankAccountType = "loan"
	UpdateBankAccountTypeOtherLiability UpdateBankAccountType = "other_liability"
)

func (e UpdateBankAccountType) ToPointer() *UpdateBankAccountType {
	return &e
}
func (e *UpdateBankAccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "depository":
		fallthrough
	case "credit":
		fallthrough
	case "other_asset":
		fallthrough
	case "loan":
		fallthrough
	case "other_liability":
		*e = UpdateBankAccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateBankAccountType: %v", v)
	}
}

// UpdateBankAccountRequestBody - Schema for updating a bank account.
type UpdateBankAccountRequestBody struct {
	// The unique identifier of the bank account.
	ID *string `json:"id,omitempty"`
	// The name of the bank account.
	Name *string `json:"name,omitempty"`
	// Whether the bank account is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// Current balance of the bank account.
	Balance *float64 `json:"balance,omitempty"`
	// The currency code for the bank account (ISO 4217).
	Currency *string `json:"currency,omitempty"`
	// Type of the bank account.
	Type *UpdateBankAccountType `json:"type,omitempty"`
}

func (o *UpdateBankAccountRequestBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateBankAccountRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateBankAccountRequestBody) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *UpdateBankAccountRequestBody) GetBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *UpdateBankAccountRequestBody) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *UpdateBankAccountRequestBody) GetType() *UpdateBankAccountType {
	if o == nil {
		return nil
	}
	return o.Type
}

type UpdateBankAccountRequest struct {
	ID          string                        `pathParam:"style=simple,explode=false,name=id"`
	RequestBody *UpdateBankAccountRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateBankAccountRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateBankAccountRequest) GetRequestBody() *UpdateBankAccountRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// UpdateBankAccountResponseBody - A single bank account object response.
type UpdateBankAccountResponseBody struct {
	// Unique identifier for the bank account.
	ID string `json:"id"`
	// Name of the bank account.
	Name *string `json:"name"`
	// Currency code of the bank account (e.g., USD, EUR).
	Currency *string `json:"currency"`
	// Type of the bank account (e.g., depository, credit).
	Type *string `json:"type"`
	// Whether the bank account is enabled.
	Enabled bool `json:"enabled"`
	// Current balance of the bank account.
	Balance *float64 `json:"balance"`
	// Whether the bank account is a manual account.
	Manual *bool `json:"manual"`
}

func (o *UpdateBankAccountResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateBankAccountResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateBankAccountResponseBody) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *UpdateBankAccountResponseBody) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *UpdateBankAccountResponseBody) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *UpdateBankAccountResponseBody) GetBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *UpdateBankAccountResponseBody) GetManual() *bool {
	if o == nil {
		return nil
	}
	return o.Manual
}

type UpdateBankAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bank account updated
	Object *UpdateBankAccountResponseBody
}

func (o *UpdateBankAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateBankAccountResponse) GetObject() *UpdateBankAccountResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
