// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

// WhatsappWebhookResponseBody - Webhook processed successfully
type WhatsappWebhookResponseBody struct {
	Success bool `json:"success"`
}

func (o *WhatsappWebhookResponseBody) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

type WhatsappWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object *WhatsappWebhookResponseBody
}

func (o *WhatsappWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WhatsappWebhookResponse) GetObject() *WhatsappWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
