// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/midday-ai/midday-go/models/components"
)

type WhatsappWebhookVerifyRequest struct {
	HubMode        string `queryParam:"style=form,explode=true,name=hub.mode"`
	HubVerifyToken string `queryParam:"style=form,explode=true,name=hub.verify_token"`
	HubChallenge   string `queryParam:"style=form,explode=true,name=hub.challenge"`
}

func (o *WhatsappWebhookVerifyRequest) GetHubMode() string {
	if o == nil {
		return ""
	}
	return o.HubMode
}

func (o *WhatsappWebhookVerifyRequest) GetHubVerifyToken() string {
	if o == nil {
		return ""
	}
	return o.HubVerifyToken
}

func (o *WhatsappWebhookVerifyRequest) GetHubChallenge() string {
	if o == nil {
		return ""
	}
	return o.HubChallenge
}

type WhatsappWebhookVerifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook verified successfully
	Res *string
}

func (o *WhatsappWebhookVerifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WhatsappWebhookVerifyResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
