// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BurnRateItem struct {
	// Date for the burn rate value
	Date string `json:"date"`
	// Burn rate value for the given date
	Value float64 `json:"value"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
}

func (o *BurnRateItem) GetDate() string {
	if o == nil {
		return ""
	}
	return o.Date
}

func (o *BurnRateItem) GetValue() float64 {
	if o == nil {
		return 0.0
	}
	return o.Value
}

func (o *BurnRateItem) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}
