// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExpensesResultArray struct {
	// Date for the expense value
	Date string `json:"date"`
	// Expense value for the given date
	Value float64 `json:"value"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
	// Recurring expense value for the given date
	Recurring float64 `json:"recurring"`
	// Total expense for the given date
	Total float64 `json:"total"`
}

func (e *ExpensesResultArray) GetDate() string {
	if e == nil {
		return ""
	}
	return e.Date
}

func (e *ExpensesResultArray) GetValue() float64 {
	if e == nil {
		return 0.0
	}
	return e.Value
}

func (e *ExpensesResultArray) GetCurrency() string {
	if e == nil {
		return ""
	}
	return e.Currency
}

func (e *ExpensesResultArray) GetRecurring() float64 {
	if e == nil {
		return 0.0
	}
	return e.Recurring
}

func (e *ExpensesResultArray) GetTotal() float64 {
	if e == nil {
		return 0.0
	}
	return e.Total
}
