// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetRevenueResponseSchema struct {
	Summary RevenueSummary      `json:"summary"`
	Meta    RevenueMeta         `json:"meta"`
	Result  []RevenueResultItem `json:"result"`
}

func (g *GetRevenueResponseSchema) GetSummary() RevenueSummary {
	if g == nil {
		return RevenueSummary{}
	}
	return g.Summary
}

func (g *GetRevenueResponseSchema) GetMeta() RevenueMeta {
	if g == nil {
		return RevenueMeta{}
	}
	return g.Meta
}

func (g *GetRevenueResponseSchema) GetResult() []RevenueResultItem {
	if g == nil {
		return []RevenueResultItem{}
	}
	return g.Result
}
