// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitResultItem struct {
	// Date for the metric (ISO 8601)
	Date       string           `json:"date"`
	Percentage ProfitPercentage `json:"percentage"`
	Current    ProfitCurrent    `json:"current"`
	Previous   ProfitPrevious   `json:"previous"`
}

func (p *ProfitResultItem) GetDate() string {
	if p == nil {
		return ""
	}
	return p.Date
}

func (p *ProfitResultItem) GetPercentage() ProfitPercentage {
	if p == nil {
		return ProfitPercentage{}
	}
	return p.Percentage
}

func (p *ProfitResultItem) GetCurrent() ProfitCurrent {
	if p == nil {
		return ProfitCurrent{}
	}
	return p.Current
}

func (p *ProfitResultItem) GetPrevious() ProfitPrevious {
	if p == nil {
		return ProfitPrevious{}
	}
	return p.Previous
}
