// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitPrevious struct {
	// Date for the previous value
	Date string `json:"date"`
	// Previous value
	Value float64 `json:"value"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
}

func (p *ProfitPrevious) GetDate() string {
	if p == nil {
		return ""
	}
	return p.Date
}

func (p *ProfitPrevious) GetValue() float64 {
	if p == nil {
		return 0.0
	}
	return p.Value
}

func (p *ProfitPrevious) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}
