// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitResultItem struct {
	// Date for the metric (ISO 8601)
	Date       string           `json:"date"`
	Precentage ProfitPercentage `json:"precentage"`
	Current    ProfitCurrent    `json:"current"`
	Previous   ProfitPrevious   `json:"previous"`
}

func (o *ProfitResultItem) GetDate() string {
	if o == nil {
		return ""
	}
	return o.Date
}

func (o *ProfitResultItem) GetPrecentage() ProfitPercentage {
	if o == nil {
		return ProfitPercentage{}
	}
	return o.Precentage
}

func (o *ProfitResultItem) GetCurrent() ProfitCurrent {
	if o == nil {
		return ProfitCurrent{}
	}
	return o.Current
}

func (o *ProfitResultItem) GetPrevious() ProfitPrevious {
	if o == nil {
		return ProfitPrevious{}
	}
	return o.Previous
}
