// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitCurrent struct {
	// Date for the current value
	Date string `json:"date"`
	// Current value
	Value float64 `json:"value"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
}

func (o *ProfitCurrent) GetDate() string {
	if o == nil {
		return ""
	}
	return o.Date
}

func (o *ProfitCurrent) GetValue() float64 {
	if o == nil {
		return 0.0
	}
	return o.Value
}

func (o *ProfitCurrent) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}
