// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitSummary struct {
	// Total profit for the current period
	CurrentTotal float64 `json:"currentTotal"`
	// Total profit for the previous period
	PrevTotal float64 `json:"prevTotal"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
}

func (p *ProfitSummary) GetCurrentTotal() float64 {
	if p == nil {
		return 0.0
	}
	return p.CurrentTotal
}

func (p *ProfitSummary) GetPrevTotal() float64 {
	if p == nil {
		return 0.0
	}
	return p.PrevTotal
}

func (p *ProfitSummary) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}
