// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SpendingResultArray struct {
	// Spending category name
	Name string `json:"name"`
	// Spending category slug
	Slug string `json:"slug"`
	// Amount spent in this category
	Amount float64 `json:"amount"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
	// Color code for the category
	Color string `json:"color"`
	// Percentage of total spending for this category
	Percentage float64 `json:"percentage"`
}

func (s *SpendingResultArray) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SpendingResultArray) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *SpendingResultArray) GetAmount() float64 {
	if s == nil {
		return 0.0
	}
	return s.Amount
}

func (s *SpendingResultArray) GetCurrency() string {
	if s == nil {
		return ""
	}
	return s.Currency
}

func (s *SpendingResultArray) GetColor() string {
	if s == nil {
		return ""
	}
	return s.Color
}

func (s *SpendingResultArray) GetPercentage() float64 {
	if s == nil {
		return 0.0
	}
	return s.Percentage
}
