// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SpendingResultArray struct {
	// Spending category name
	Name string `json:"name"`
	// Spending category slug
	Slug string `json:"slug"`
	// Amount spent in this category
	Amount float64 `json:"amount"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
	// Color code for the category
	Color string `json:"color"`
	// Percentage of total spending for this category
	Percentage float64 `json:"percentage"`
}

func (o *SpendingResultArray) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SpendingResultArray) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *SpendingResultArray) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *SpendingResultArray) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *SpendingResultArray) GetColor() string {
	if o == nil {
		return ""
	}
	return o.Color
}

func (o *SpendingResultArray) GetPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Percentage
}
