// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TrackerProjectsResponseMeta - Pagination metadata for the projects response
type TrackerProjectsResponseMeta struct {
	// Whether there are more projects available on the next page
	HasNextPage bool `json:"hasNextPage"`
	// Whether there are more projects available on the previous page
	HasPreviousPage bool `json:"hasPreviousPage"`
}

func (t *TrackerProjectsResponseMeta) GetHasNextPage() bool {
	if t == nil {
		return false
	}
	return t.HasNextPage
}

func (t *TrackerProjectsResponseMeta) GetHasPreviousPage() bool {
	if t == nil {
		return false
	}
	return t.HasPreviousPage
}

type TrackerProjectsResponse struct {
	// Pagination metadata for the projects response
	Meta TrackerProjectsResponseMeta `json:"meta"`
	// Array of tracker projects matching the query criteria
	Data []TrackerProjectResponse `json:"data"`
}

func (t *TrackerProjectsResponse) GetMeta() TrackerProjectsResponseMeta {
	if t == nil {
		return TrackerProjectsResponseMeta{}
	}
	return t.Meta
}

func (t *TrackerProjectsResponse) GetData() []TrackerProjectResponse {
	if t == nil {
		return []TrackerProjectResponse{}
	}
	return t.Data
}
