// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Category information assigned to the transaction for organization
type Category struct {
	// Unique identifier of the category
	ID string `json:"id"`
	// Display name of the category
	Name string `json:"name"`
	// Hex color code associated with the category for UI display
	Color string `json:"color"`
	// Tax rate of the category
	TaxRate *float64 `json:"taxRate"`
	// Tax type of the category
	TaxType *string `json:"taxType"`
	// URL-friendly slug of the category
	Slug string `json:"slug"`
}

func (c *Category) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Category) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Category) GetColor() string {
	if c == nil {
		return ""
	}
	return c.Color
}

func (c *Category) GetTaxRate() *float64 {
	if c == nil {
		return nil
	}
	return c.TaxRate
}

func (c *Category) GetTaxType() *string {
	if c == nil {
		return nil
	}
	return c.TaxType
}

func (c *Category) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

// Connection - Bank connection information associated with the account
type Connection struct {
	// Unique identifier of the bank connection
	ID string `json:"id"`
	// Name of the bank institution
	Name string `json:"name"`
	// URL to the bank institution's logo image
	LogoURL *string `json:"logoUrl"`
}

func (c *Connection) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Connection) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Connection) GetLogoURL() *string {
	if c == nil {
		return nil
	}
	return c.LogoURL
}

// Account - Bank account information associated with the transaction
type Account struct {
	// Unique identifier of the bank account
	ID string `json:"id"`
	// Display name of the bank account
	Name string `json:"name"`
	// Currency of the bank account in ISO 4217 format
	Currency string `json:"currency"`
	// Bank connection information associated with the account
	Connection Connection `json:"connection"`
}

func (a *Account) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Account) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *Account) GetCurrency() string {
	if a == nil {
		return ""
	}
	return a.Currency
}

func (a *Account) GetConnection() Connection {
	if a == nil {
		return Connection{}
	}
	return a.Connection
}

type TransactionResponseTag struct {
	// Unique identifier of the tag
	ID string `json:"id"`
	// Display name of the tag
	Name *string `json:"name"`
}

func (t *TransactionResponseTag) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TransactionResponseTag) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

type Attachment struct {
	// Unique identifier of the attachment
	ID string `json:"id"`
	// Array of path segments for the attachment file storage location
	Path []string `json:"path"`
	// Size of the attachment file in bytes
	Size float64 `json:"size"`
	// MIME type of the attachment file
	Type string `json:"type"`
	// Original filename of the attachment when uploaded
	Filename *string `json:"filename"`
}

func (a *Attachment) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Attachment) GetPath() []string {
	if a == nil {
		return []string{}
	}
	return a.Path
}

func (a *Attachment) GetSize() float64 {
	if a == nil {
		return 0.0
	}
	return a.Size
}

func (a *Attachment) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *Attachment) GetFilename() *string {
	if a == nil {
		return nil
	}
	return a.Filename
}

type TransactionResponse struct {
	// Unique identifier of the transaction
	ID string `json:"id"`
	// Name or description of the transaction
	Name string `json:"name"`
	// Monetary amount of the transaction
	Amount float64 `json:"amount"`
	// Tax amount of the transaction
	TaxAmount *float64 `json:"taxAmount"`
	// Tax rate of the transaction
	TaxRate *float64 `json:"taxRate"`
	// Tax type of the transaction
	TaxType *string `json:"taxType"`
	// Currency code of the transaction in ISO 4217 format
	Currency string `json:"currency"`
	// Name of the counterparty
	CounterpartyName *string `json:"counterpartyName"`
	// Date and time of the transaction in ISO 8601 format
	Date string `json:"date"`
	// Category information assigned to the transaction for organization
	Category *Category `json:"category"`
	// Current status of the transaction
	Status string `json:"status"`
	// Whether the transaction is internal (between own accounts)
	Internal *bool `json:"internal"`
	// Whether the transaction is part of a recurring series
	Recurring *bool `json:"recurring"`
	// Whether the transaction was created manually (via API/form) rather than imported from bank connections
	Manual *bool `json:"manual"`
	// Frequency of the recurring transaction if applicable (weekly, monthly, annually, irregular)
	Frequency *string `json:"frequency"`
	// Whether the transaction has been fulfilled or processed
	IsFulfilled bool `json:"isFulfilled"`
	// Optional note or memo attached to the transaction
	Note *string `json:"note"`
	// Bank account information associated with the transaction
	Account Account `json:"account"`
	// Array of tags associated with the transaction for categorization and filtering
	Tags []TransactionResponseTag `json:"tags"`
	// Array of file attachments associated with the transaction (receipts, invoices, etc.)
	Attachments []Attachment `json:"attachments"`
}

func (t *TransactionResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TransactionResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TransactionResponse) GetAmount() float64 {
	if t == nil {
		return 0.0
	}
	return t.Amount
}

func (t *TransactionResponse) GetTaxAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.TaxAmount
}

func (t *TransactionResponse) GetTaxRate() *float64 {
	if t == nil {
		return nil
	}
	return t.TaxRate
}

func (t *TransactionResponse) GetTaxType() *string {
	if t == nil {
		return nil
	}
	return t.TaxType
}

func (t *TransactionResponse) GetCurrency() string {
	if t == nil {
		return ""
	}
	return t.Currency
}

func (t *TransactionResponse) GetCounterpartyName() *string {
	if t == nil {
		return nil
	}
	return t.CounterpartyName
}

func (t *TransactionResponse) GetDate() string {
	if t == nil {
		return ""
	}
	return t.Date
}

func (t *TransactionResponse) GetCategory() *Category {
	if t == nil {
		return nil
	}
	return t.Category
}

func (t *TransactionResponse) GetStatus() string {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *TransactionResponse) GetInternal() *bool {
	if t == nil {
		return nil
	}
	return t.Internal
}

func (t *TransactionResponse) GetRecurring() *bool {
	if t == nil {
		return nil
	}
	return t.Recurring
}

func (t *TransactionResponse) GetManual() *bool {
	if t == nil {
		return nil
	}
	return t.Manual
}

func (t *TransactionResponse) GetFrequency() *string {
	if t == nil {
		return nil
	}
	return t.Frequency
}

func (t *TransactionResponse) GetIsFulfilled() bool {
	if t == nil {
		return false
	}
	return t.IsFulfilled
}

func (t *TransactionResponse) GetNote() *string {
	if t == nil {
		return nil
	}
	return t.Note
}

func (t *TransactionResponse) GetAccount() Account {
	if t == nil {
		return Account{}
	}
	return t.Account
}

func (t *TransactionResponse) GetTags() []TransactionResponseTag {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *TransactionResponse) GetAttachments() []Attachment {
	if t == nil {
		return nil
	}
	return t.Attachments
}
