// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateAllNotificationsStatusResponseSchema struct {
	// Array of updated notifications
	Data []NotificationSchema `json:"data"`
}

func (u *UpdateAllNotificationsStatusResponseSchema) GetData() []NotificationSchema {
	if u == nil {
		return []NotificationSchema{}
	}
	return u.Data
}
