// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/midday-ai/midday-go/models/components"
)

// PostOAuthTokenBadRequestError - Invalid request
type PostOAuthTokenBadRequestError struct {
	// Error code
	Error_ string `json:"error"`
	// Human-readable error description
	ErrorDescription *string `json:"error_description,omitempty"`
	// URI to a human-readable error page
	ErrorURI *string `json:"error_uri,omitempty"`
	// State parameter from the original request (min 32 chars, alphanumeric + _.-)
	State    *string                 `json:"state,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostOAuthTokenBadRequestError{}

func (e *PostOAuthTokenBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
