// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/midday-ai/midday-go/models/components"
)

// SlackOAuthCallbackInternalServerError - Failed to process OAuth callback
type SlackOAuthCallbackInternalServerError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SlackOAuthCallbackInternalServerError{}

func (e *SlackOAuthCallbackInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// SlackOAuthCallbackBadRequestError - Invalid request parameters
type SlackOAuthCallbackBadRequestError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SlackOAuthCallbackBadRequestError{}

func (e *SlackOAuthCallbackBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
